// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/backend/internal/data/model"
)

func newAuthSession(db *gorm.DB, opts ...gen.DOOption) authSession {
	_authSession := authSession{}

	_authSession.authSessionDo.UseDB(db, opts...)
	_authSession.authSessionDo.UseModel(&model.AuthSession{})

	tableName := _authSession.authSessionDo.TableName()
	_authSession.ALL = field.NewAsterisk(tableName)
	_authSession.ID = field.NewString(tableName, "id")
	_authSession.UserID = field.NewUint64(tableName, "user_id")
	_authSession.TenantID = field.NewUint64(tableName, "tenant_id")
	_authSession.MemberID = field.NewUint64(tableName, "member_id")
	_authSession.PermissionVersion = field.NewUint64(tableName, "permission_version")
	_authSession.RefreshJTIHash = field.NewString(tableName, "refresh_jti_hash")
	_authSession.DeviceName = field.NewString(tableName, "device_name")
	_authSession.UserAgent = field.NewString(tableName, "user_agent")
	_authSession.IP = field.NewString(tableName, "ip")
	_authSession.ExpiresAt = field.NewTime(tableName, "expires_at")
	_authSession.RevokedAt = field.NewTime(tableName, "revoked_at")
	_authSession.CreatedAt = field.NewTime(tableName, "created_at")
	_authSession.UpdatedAt = field.NewTime(tableName, "updated_at")

	_authSession.fillFieldMap()

	return _authSession
}

type authSession struct {
	authSessionDo authSessionDo

	ALL               field.Asterisk
	ID                field.String
	UserID            field.Uint64
	TenantID          field.Uint64
	MemberID          field.Uint64
	PermissionVersion field.Uint64
	RefreshJTIHash    field.String
	DeviceName        field.String
	UserAgent         field.String
	IP                field.String
	ExpiresAt         field.Time
	RevokedAt         field.Time
	CreatedAt         field.Time
	UpdatedAt         field.Time

	fieldMap map[string]field.Expr
}

func (a authSession) Table(newTableName string) *authSession {
	a.authSessionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authSession) As(alias string) *authSession {
	a.authSessionDo.DO = *(a.authSessionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authSession) updateTableName(table string) *authSession {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.UserID = field.NewUint64(table, "user_id")
	a.TenantID = field.NewUint64(table, "tenant_id")
	a.MemberID = field.NewUint64(table, "member_id")
	a.PermissionVersion = field.NewUint64(table, "permission_version")
	a.RefreshJTIHash = field.NewString(table, "refresh_jti_hash")
	a.DeviceName = field.NewString(table, "device_name")
	a.UserAgent = field.NewString(table, "user_agent")
	a.IP = field.NewString(table, "ip")
	a.ExpiresAt = field.NewTime(table, "expires_at")
	a.RevokedAt = field.NewTime(table, "revoked_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *authSession) WithContext(ctx context.Context) IAuthSessionDo {
	return a.authSessionDo.WithContext(ctx)
}

func (a authSession) TableName() string { return a.authSessionDo.TableName() }

func (a authSession) Alias() string { return a.authSessionDo.Alias() }

func (a authSession) Columns(cols ...field.Expr) gen.Columns { return a.authSessionDo.Columns(cols...) }

func (a *authSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authSession) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["tenant_id"] = a.TenantID
	a.fieldMap["member_id"] = a.MemberID
	a.fieldMap["permission_version"] = a.PermissionVersion
	a.fieldMap["refresh_jti_hash"] = a.RefreshJTIHash
	a.fieldMap["device_name"] = a.DeviceName
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["ip"] = a.IP
	a.fieldMap["expires_at"] = a.ExpiresAt
	a.fieldMap["revoked_at"] = a.RevokedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a authSession) clone(db *gorm.DB) authSession {
	a.authSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authSession) replaceDB(db *gorm.DB) authSession {
	a.authSessionDo.ReplaceDB(db)
	return a
}

type authSessionDo struct{ gen.DO }

type IAuthSessionDo interface {
	gen.SubQuery
	Debug() IAuthSessionDo
	WithContext(ctx context.Context) IAuthSessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAuthSessionDo
	WriteDB() IAuthSessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAuthSessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAuthSessionDo
	Not(conds ...gen.Condition) IAuthSessionDo
	Or(conds ...gen.Condition) IAuthSessionDo
	Select(conds ...field.Expr) IAuthSessionDo
	Where(conds ...gen.Condition) IAuthSessionDo
	Order(conds ...field.Expr) IAuthSessionDo
	Distinct(cols ...field.Expr) IAuthSessionDo
	Omit(cols ...field.Expr) IAuthSessionDo
	Join(table schema.Tabler, on ...field.Expr) IAuthSessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAuthSessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAuthSessionDo
	Group(cols ...field.Expr) IAuthSessionDo
	Having(conds ...gen.Condition) IAuthSessionDo
	Limit(limit int) IAuthSessionDo
	Offset(offset int) IAuthSessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthSessionDo
	Unscoped() IAuthSessionDo
	Create(values ...*model.AuthSession) error
	CreateInBatches(values []*model.AuthSession, batchSize int) error
	Save(values ...*model.AuthSession) error
	First() (*model.AuthSession, error)
	Take() (*model.AuthSession, error)
	Last() (*model.AuthSession, error)
	Find() ([]*model.AuthSession, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthSession, err error)
	FindInBatches(result *[]*model.AuthSession, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AuthSession) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAuthSessionDo
	Assign(attrs ...field.AssignExpr) IAuthSessionDo
	Joins(fields ...field.RelationField) IAuthSessionDo
	Preload(fields ...field.RelationField) IAuthSessionDo
	FirstOrInit() (*model.AuthSession, error)
	FirstOrCreate() (*model.AuthSession, error)
	FindByPage(offset int, limit int) (result []*model.AuthSession, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAuthSessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a authSessionDo) Debug() IAuthSessionDo {
	return a.withDO(a.DO.Debug())
}

func (a authSessionDo) WithContext(ctx context.Context) IAuthSessionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authSessionDo) ReadDB() IAuthSessionDo {
	return a.Clauses(dbresolver.Read)
}

func (a authSessionDo) WriteDB() IAuthSessionDo {
	return a.Clauses(dbresolver.Write)
}

func (a authSessionDo) Session(config *gorm.Session) IAuthSessionDo {
	return a.withDO(a.DO.Session(config))
}

func (a authSessionDo) Clauses(conds ...clause.Expression) IAuthSessionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authSessionDo) Returning(value interface{}, columns ...string) IAuthSessionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authSessionDo) Not(conds ...gen.Condition) IAuthSessionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authSessionDo) Or(conds ...gen.Condition) IAuthSessionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authSessionDo) Select(conds ...field.Expr) IAuthSessionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authSessionDo) Where(conds ...gen.Condition) IAuthSessionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authSessionDo) Order(conds ...field.Expr) IAuthSessionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authSessionDo) Distinct(cols ...field.Expr) IAuthSessionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authSessionDo) Omit(cols ...field.Expr) IAuthSessionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authSessionDo) Join(table schema.Tabler, on ...field.Expr) IAuthSessionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAuthSessionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) IAuthSessionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authSessionDo) Group(cols ...field.Expr) IAuthSessionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authSessionDo) Having(conds ...gen.Condition) IAuthSessionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authSessionDo) Limit(limit int) IAuthSessionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authSessionDo) Offset(offset int) IAuthSessionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthSessionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authSessionDo) Unscoped() IAuthSessionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authSessionDo) Create(values ...*model.AuthSession) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authSessionDo) CreateInBatches(values []*model.AuthSession, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authSessionDo) Save(values ...*model.AuthSession) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authSessionDo) First() (*model.AuthSession, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) Take() (*model.AuthSession, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) Last() (*model.AuthSession, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) Find() ([]*model.AuthSession, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuthSession), err
}

func (a authSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthSession, err error) {
	buf := make([]*model.AuthSession, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authSessionDo) FindInBatches(result *[]*model.AuthSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authSessionDo) Attrs(attrs ...field.AssignExpr) IAuthSessionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authSessionDo) Assign(attrs ...field.AssignExpr) IAuthSessionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authSessionDo) Joins(fields ...field.RelationField) IAuthSessionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authSessionDo) Preload(fields ...field.RelationField) IAuthSessionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authSessionDo) FirstOrInit() (*model.AuthSession, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) FirstOrCreate() (*model.AuthSession, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) FindByPage(offset int, limit int) (result []*model.AuthSession, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authSessionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authSessionDo) Delete(models ...*model.AuthSession) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authSessionDo) withDO(do gen.Dao) *authSessionDo {
	a.DO = *do.(*gen.DO)
	return a
}
