// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/backend/internal/data/model"
)

func newFileReference(db *gorm.DB, opts ...gen.DOOption) fileReference {
	_fileReference := fileReference{}

	_fileReference.fileReferenceDo.UseDB(db, opts...)
	_fileReference.fileReferenceDo.UseModel(&model.FileReference{})

	tableName := _fileReference.fileReferenceDo.TableName()
	_fileReference.ALL = field.NewAsterisk(tableName)
	_fileReference.ID = field.NewUint64(tableName, "id")
	_fileReference.TenantID = field.NewUint64(tableName, "tenant_id")
	_fileReference.FileID = field.NewString(tableName, "file_id")
	_fileReference.BusinessType = field.NewString(tableName, "business_type")
	_fileReference.BusinessID = field.NewString(tableName, "business_id")
	_fileReference.CreatedAt = field.NewTime(tableName, "created_at")

	_fileReference.fillFieldMap()

	return _fileReference
}

type fileReference struct {
	fileReferenceDo fileReferenceDo

	ALL          field.Asterisk
	ID           field.Uint64
	TenantID     field.Uint64
	FileID       field.String
	BusinessType field.String
	BusinessID   field.String
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (f fileReference) Table(newTableName string) *fileReference {
	f.fileReferenceDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fileReference) As(alias string) *fileReference {
	f.fileReferenceDo.DO = *(f.fileReferenceDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fileReference) updateTableName(table string) *fileReference {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewUint64(table, "id")
	f.TenantID = field.NewUint64(table, "tenant_id")
	f.FileID = field.NewString(table, "file_id")
	f.BusinessType = field.NewString(table, "business_type")
	f.BusinessID = field.NewString(table, "business_id")
	f.CreatedAt = field.NewTime(table, "created_at")

	f.fillFieldMap()

	return f
}

func (f *fileReference) WithContext(ctx context.Context) IFileReferenceDo {
	return f.fileReferenceDo.WithContext(ctx)
}

func (f fileReference) TableName() string { return f.fileReferenceDo.TableName() }

func (f fileReference) Alias() string { return f.fileReferenceDo.Alias() }

func (f fileReference) Columns(cols ...field.Expr) gen.Columns {
	return f.fileReferenceDo.Columns(cols...)
}

func (f *fileReference) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fileReference) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 6)
	f.fieldMap["id"] = f.ID
	f.fieldMap["tenant_id"] = f.TenantID
	f.fieldMap["file_id"] = f.FileID
	f.fieldMap["business_type"] = f.BusinessType
	f.fieldMap["business_id"] = f.BusinessID
	f.fieldMap["created_at"] = f.CreatedAt
}

func (f fileReference) clone(db *gorm.DB) fileReference {
	f.fileReferenceDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fileReference) replaceDB(db *gorm.DB) fileReference {
	f.fileReferenceDo.ReplaceDB(db)
	return f
}

type fileReferenceDo struct{ gen.DO }

type IFileReferenceDo interface {
	gen.SubQuery
	Debug() IFileReferenceDo
	WithContext(ctx context.Context) IFileReferenceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFileReferenceDo
	WriteDB() IFileReferenceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFileReferenceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFileReferenceDo
	Not(conds ...gen.Condition) IFileReferenceDo
	Or(conds ...gen.Condition) IFileReferenceDo
	Select(conds ...field.Expr) IFileReferenceDo
	Where(conds ...gen.Condition) IFileReferenceDo
	Order(conds ...field.Expr) IFileReferenceDo
	Distinct(cols ...field.Expr) IFileReferenceDo
	Omit(cols ...field.Expr) IFileReferenceDo
	Join(table schema.Tabler, on ...field.Expr) IFileReferenceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFileReferenceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFileReferenceDo
	Group(cols ...field.Expr) IFileReferenceDo
	Having(conds ...gen.Condition) IFileReferenceDo
	Limit(limit int) IFileReferenceDo
	Offset(offset int) IFileReferenceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFileReferenceDo
	Unscoped() IFileReferenceDo
	Create(values ...*model.FileReference) error
	CreateInBatches(values []*model.FileReference, batchSize int) error
	Save(values ...*model.FileReference) error
	First() (*model.FileReference, error)
	Take() (*model.FileReference, error)
	Last() (*model.FileReference, error)
	Find() ([]*model.FileReference, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FileReference, err error)
	FindInBatches(result *[]*model.FileReference, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FileReference) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFileReferenceDo
	Assign(attrs ...field.AssignExpr) IFileReferenceDo
	Joins(fields ...field.RelationField) IFileReferenceDo
	Preload(fields ...field.RelationField) IFileReferenceDo
	FirstOrInit() (*model.FileReference, error)
	FirstOrCreate() (*model.FileReference, error)
	FindByPage(offset int, limit int) (result []*model.FileReference, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFileReferenceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fileReferenceDo) Debug() IFileReferenceDo {
	return f.withDO(f.DO.Debug())
}

func (f fileReferenceDo) WithContext(ctx context.Context) IFileReferenceDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileReferenceDo) ReadDB() IFileReferenceDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileReferenceDo) WriteDB() IFileReferenceDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileReferenceDo) Session(config *gorm.Session) IFileReferenceDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileReferenceDo) Clauses(conds ...clause.Expression) IFileReferenceDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileReferenceDo) Returning(value interface{}, columns ...string) IFileReferenceDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileReferenceDo) Not(conds ...gen.Condition) IFileReferenceDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileReferenceDo) Or(conds ...gen.Condition) IFileReferenceDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileReferenceDo) Select(conds ...field.Expr) IFileReferenceDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileReferenceDo) Where(conds ...gen.Condition) IFileReferenceDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileReferenceDo) Order(conds ...field.Expr) IFileReferenceDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileReferenceDo) Distinct(cols ...field.Expr) IFileReferenceDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileReferenceDo) Omit(cols ...field.Expr) IFileReferenceDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileReferenceDo) Join(table schema.Tabler, on ...field.Expr) IFileReferenceDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileReferenceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFileReferenceDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileReferenceDo) RightJoin(table schema.Tabler, on ...field.Expr) IFileReferenceDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileReferenceDo) Group(cols ...field.Expr) IFileReferenceDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileReferenceDo) Having(conds ...gen.Condition) IFileReferenceDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileReferenceDo) Limit(limit int) IFileReferenceDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileReferenceDo) Offset(offset int) IFileReferenceDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileReferenceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFileReferenceDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileReferenceDo) Unscoped() IFileReferenceDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileReferenceDo) Create(values ...*model.FileReference) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileReferenceDo) CreateInBatches(values []*model.FileReference, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileReferenceDo) Save(values ...*model.FileReference) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileReferenceDo) First() (*model.FileReference, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileReference), nil
	}
}

func (f fileReferenceDo) Take() (*model.FileReference, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileReference), nil
	}
}

func (f fileReferenceDo) Last() (*model.FileReference, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileReference), nil
	}
}

func (f fileReferenceDo) Find() ([]*model.FileReference, error) {
	result, err := f.DO.Find()
	return result.([]*model.FileReference), err
}

func (f fileReferenceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FileReference, err error) {
	buf := make([]*model.FileReference, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileReferenceDo) FindInBatches(result *[]*model.FileReference, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileReferenceDo) Attrs(attrs ...field.AssignExpr) IFileReferenceDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileReferenceDo) Assign(attrs ...field.AssignExpr) IFileReferenceDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileReferenceDo) Joins(fields ...field.RelationField) IFileReferenceDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileReferenceDo) Preload(fields ...field.RelationField) IFileReferenceDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileReferenceDo) FirstOrInit() (*model.FileReference, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileReference), nil
	}
}

func (f fileReferenceDo) FirstOrCreate() (*model.FileReference, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileReference), nil
	}
}

func (f fileReferenceDo) FindByPage(offset int, limit int) (result []*model.FileReference, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileReferenceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileReferenceDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileReferenceDo) Delete(models ...*model.FileReference) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileReferenceDo) withDO(do gen.Dao) *fileReferenceDo {
	f.DO = *do.(*gen.DO)
	return f
}
