// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/backend/internal/data/model"
)

func newProviderConfig(db *gorm.DB, opts ...gen.DOOption) providerConfig {
	_providerConfig := providerConfig{}

	_providerConfig.providerConfigDo.UseDB(db, opts...)
	_providerConfig.providerConfigDo.UseModel(&model.ProviderConfig{})

	tableName := _providerConfig.providerConfigDo.TableName()
	_providerConfig.ALL = field.NewAsterisk(tableName)
	_providerConfig.ID = field.NewUint64(tableName, "id")
	_providerConfig.TenantID = field.NewUint64(tableName, "tenant_id")
	_providerConfig.ProviderType = field.NewString(tableName, "provider_type")
	_providerConfig.ProviderName = field.NewString(tableName, "provider_name")
	_providerConfig.DisplayName = field.NewString(tableName, "display_name")
	_providerConfig.EncryptedConfig = field.NewString(tableName, "encrypted_config")
	_providerConfig.Status = field.NewUint8(tableName, "status")
	_providerConfig.IsDefault = field.NewBool(tableName, "is_default")
	_providerConfig.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_providerConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_providerConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_providerConfig.fillFieldMap()

	return _providerConfig
}

type providerConfig struct {
	providerConfigDo providerConfigDo

	ALL             field.Asterisk
	ID              field.Uint64
	TenantID        field.Uint64
	ProviderType    field.String
	ProviderName    field.String
	DisplayName     field.String
	EncryptedConfig field.String
	Status          field.Uint8
	IsDefault       field.Bool
	UpdatedBy       field.Uint64
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (p providerConfig) Table(newTableName string) *providerConfig {
	p.providerConfigDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p providerConfig) As(alias string) *providerConfig {
	p.providerConfigDo.DO = *(p.providerConfigDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *providerConfig) updateTableName(table string) *providerConfig {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint64(table, "id")
	p.TenantID = field.NewUint64(table, "tenant_id")
	p.ProviderType = field.NewString(table, "provider_type")
	p.ProviderName = field.NewString(table, "provider_name")
	p.DisplayName = field.NewString(table, "display_name")
	p.EncryptedConfig = field.NewString(table, "encrypted_config")
	p.Status = field.NewUint8(table, "status")
	p.IsDefault = field.NewBool(table, "is_default")
	p.UpdatedBy = field.NewUint64(table, "updated_by")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *providerConfig) WithContext(ctx context.Context) IProviderConfigDo {
	return p.providerConfigDo.WithContext(ctx)
}

func (p providerConfig) TableName() string { return p.providerConfigDo.TableName() }

func (p providerConfig) Alias() string { return p.providerConfigDo.Alias() }

func (p providerConfig) Columns(cols ...field.Expr) gen.Columns {
	return p.providerConfigDo.Columns(cols...)
}

func (p *providerConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *providerConfig) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["id"] = p.ID
	p.fieldMap["tenant_id"] = p.TenantID
	p.fieldMap["provider_type"] = p.ProviderType
	p.fieldMap["provider_name"] = p.ProviderName
	p.fieldMap["display_name"] = p.DisplayName
	p.fieldMap["encrypted_config"] = p.EncryptedConfig
	p.fieldMap["status"] = p.Status
	p.fieldMap["is_default"] = p.IsDefault
	p.fieldMap["updated_by"] = p.UpdatedBy
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p providerConfig) clone(db *gorm.DB) providerConfig {
	p.providerConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p providerConfig) replaceDB(db *gorm.DB) providerConfig {
	p.providerConfigDo.ReplaceDB(db)
	return p
}

type providerConfigDo struct{ gen.DO }

type IProviderConfigDo interface {
	gen.SubQuery
	Debug() IProviderConfigDo
	WithContext(ctx context.Context) IProviderConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProviderConfigDo
	WriteDB() IProviderConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProviderConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProviderConfigDo
	Not(conds ...gen.Condition) IProviderConfigDo
	Or(conds ...gen.Condition) IProviderConfigDo
	Select(conds ...field.Expr) IProviderConfigDo
	Where(conds ...gen.Condition) IProviderConfigDo
	Order(conds ...field.Expr) IProviderConfigDo
	Distinct(cols ...field.Expr) IProviderConfigDo
	Omit(cols ...field.Expr) IProviderConfigDo
	Join(table schema.Tabler, on ...field.Expr) IProviderConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProviderConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProviderConfigDo
	Group(cols ...field.Expr) IProviderConfigDo
	Having(conds ...gen.Condition) IProviderConfigDo
	Limit(limit int) IProviderConfigDo
	Offset(offset int) IProviderConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProviderConfigDo
	Unscoped() IProviderConfigDo
	Create(values ...*model.ProviderConfig) error
	CreateInBatches(values []*model.ProviderConfig, batchSize int) error
	Save(values ...*model.ProviderConfig) error
	First() (*model.ProviderConfig, error)
	Take() (*model.ProviderConfig, error)
	Last() (*model.ProviderConfig, error)
	Find() ([]*model.ProviderConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProviderConfig, err error)
	FindInBatches(result *[]*model.ProviderConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProviderConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProviderConfigDo
	Assign(attrs ...field.AssignExpr) IProviderConfigDo
	Joins(fields ...field.RelationField) IProviderConfigDo
	Preload(fields ...field.RelationField) IProviderConfigDo
	FirstOrInit() (*model.ProviderConfig, error)
	FirstOrCreate() (*model.ProviderConfig, error)
	FindByPage(offset int, limit int) (result []*model.ProviderConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProviderConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p providerConfigDo) Debug() IProviderConfigDo {
	return p.withDO(p.DO.Debug())
}

func (p providerConfigDo) WithContext(ctx context.Context) IProviderConfigDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p providerConfigDo) ReadDB() IProviderConfigDo {
	return p.Clauses(dbresolver.Read)
}

func (p providerConfigDo) WriteDB() IProviderConfigDo {
	return p.Clauses(dbresolver.Write)
}

func (p providerConfigDo) Session(config *gorm.Session) IProviderConfigDo {
	return p.withDO(p.DO.Session(config))
}

func (p providerConfigDo) Clauses(conds ...clause.Expression) IProviderConfigDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p providerConfigDo) Returning(value interface{}, columns ...string) IProviderConfigDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p providerConfigDo) Not(conds ...gen.Condition) IProviderConfigDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p providerConfigDo) Or(conds ...gen.Condition) IProviderConfigDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p providerConfigDo) Select(conds ...field.Expr) IProviderConfigDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p providerConfigDo) Where(conds ...gen.Condition) IProviderConfigDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p providerConfigDo) Order(conds ...field.Expr) IProviderConfigDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p providerConfigDo) Distinct(cols ...field.Expr) IProviderConfigDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p providerConfigDo) Omit(cols ...field.Expr) IProviderConfigDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p providerConfigDo) Join(table schema.Tabler, on ...field.Expr) IProviderConfigDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p providerConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProviderConfigDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p providerConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IProviderConfigDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p providerConfigDo) Group(cols ...field.Expr) IProviderConfigDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p providerConfigDo) Having(conds ...gen.Condition) IProviderConfigDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p providerConfigDo) Limit(limit int) IProviderConfigDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p providerConfigDo) Offset(offset int) IProviderConfigDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p providerConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProviderConfigDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p providerConfigDo) Unscoped() IProviderConfigDo {
	return p.withDO(p.DO.Unscoped())
}

func (p providerConfigDo) Create(values ...*model.ProviderConfig) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p providerConfigDo) CreateInBatches(values []*model.ProviderConfig, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p providerConfigDo) Save(values ...*model.ProviderConfig) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p providerConfigDo) First() (*model.ProviderConfig, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProviderConfig), nil
	}
}

func (p providerConfigDo) Take() (*model.ProviderConfig, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProviderConfig), nil
	}
}

func (p providerConfigDo) Last() (*model.ProviderConfig, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProviderConfig), nil
	}
}

func (p providerConfigDo) Find() ([]*model.ProviderConfig, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProviderConfig), err
}

func (p providerConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProviderConfig, err error) {
	buf := make([]*model.ProviderConfig, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p providerConfigDo) FindInBatches(result *[]*model.ProviderConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p providerConfigDo) Attrs(attrs ...field.AssignExpr) IProviderConfigDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p providerConfigDo) Assign(attrs ...field.AssignExpr) IProviderConfigDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p providerConfigDo) Joins(fields ...field.RelationField) IProviderConfigDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p providerConfigDo) Preload(fields ...field.RelationField) IProviderConfigDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p providerConfigDo) FirstOrInit() (*model.ProviderConfig, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProviderConfig), nil
	}
}

func (p providerConfigDo) FirstOrCreate() (*model.ProviderConfig, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProviderConfig), nil
	}
}

func (p providerConfigDo) FindByPage(offset int, limit int) (result []*model.ProviderConfig, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p providerConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p providerConfigDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p providerConfigDo) Delete(models ...*model.ProviderConfig) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *providerConfigDo) withDO(do gen.Dao) *providerConfigDo {
	p.DO = *do.(*gen.DO)
	return p
}
