// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/backend/internal/data/model"
)

func newResource(db *gorm.DB, opts ...gen.DOOption) resource {
	_resource := resource{}

	_resource.resourceDo.UseDB(db, opts...)
	_resource.resourceDo.UseModel(&model.Resource{})

	tableName := _resource.resourceDo.TableName()
	_resource.ALL = field.NewAsterisk(tableName)
	_resource.ID = field.NewUint64(tableName, "id")
	_resource.ParentID = field.NewUint64(tableName, "parent_id")
	_resource.Type = field.NewUint8(tableName, "type")
	_resource.Code = field.NewString(tableName, "code")
	_resource.Name = field.NewString(tableName, "name")
	_resource.RoutePath = field.NewString(tableName, "route_path")
	_resource.ComponentKey = field.NewString(tableName, "component_key")
	_resource.HTTPMethod = field.NewString(tableName, "http_method")
	_resource.APIPath = field.NewString(tableName, "api_path")
	_resource.Icon = field.NewString(tableName, "icon")
	_resource.SortOrder = field.NewInt(tableName, "sort_order")
	_resource.Visible = field.NewBool(tableName, "visible")
	_resource.Status = field.NewUint8(tableName, "status")
	_resource.CreatedAt = field.NewTime(tableName, "created_at")
	_resource.UpdatedAt = field.NewTime(tableName, "updated_at")
	_resource.DeletedAt = field.NewField(tableName, "deleted_at")

	_resource.fillFieldMap()

	return _resource
}

type resource struct {
	resourceDo resourceDo

	ALL          field.Asterisk
	ID           field.Uint64
	ParentID     field.Uint64
	Type         field.Uint8
	Code         field.String
	Name         field.String
	RoutePath    field.String
	ComponentKey field.String
	HTTPMethod   field.String
	APIPath      field.String
	Icon         field.String
	SortOrder    field.Int
	Visible      field.Bool
	Status       field.Uint8
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field

	fieldMap map[string]field.Expr
}

func (r resource) Table(newTableName string) *resource {
	r.resourceDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resource) As(alias string) *resource {
	r.resourceDo.DO = *(r.resourceDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resource) updateTableName(table string) *resource {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint64(table, "id")
	r.ParentID = field.NewUint64(table, "parent_id")
	r.Type = field.NewUint8(table, "type")
	r.Code = field.NewString(table, "code")
	r.Name = field.NewString(table, "name")
	r.RoutePath = field.NewString(table, "route_path")
	r.ComponentKey = field.NewString(table, "component_key")
	r.HTTPMethod = field.NewString(table, "http_method")
	r.APIPath = field.NewString(table, "api_path")
	r.Icon = field.NewString(table, "icon")
	r.SortOrder = field.NewInt(table, "sort_order")
	r.Visible = field.NewBool(table, "visible")
	r.Status = field.NewUint8(table, "status")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *resource) WithContext(ctx context.Context) IResourceDo { return r.resourceDo.WithContext(ctx) }

func (r resource) TableName() string { return r.resourceDo.TableName() }

func (r resource) Alias() string { return r.resourceDo.Alias() }

func (r resource) Columns(cols ...field.Expr) gen.Columns { return r.resourceDo.Columns(cols...) }

func (r *resource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resource) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 16)
	r.fieldMap["id"] = r.ID
	r.fieldMap["parent_id"] = r.ParentID
	r.fieldMap["type"] = r.Type
	r.fieldMap["code"] = r.Code
	r.fieldMap["name"] = r.Name
	r.fieldMap["route_path"] = r.RoutePath
	r.fieldMap["component_key"] = r.ComponentKey
	r.fieldMap["http_method"] = r.HTTPMethod
	r.fieldMap["api_path"] = r.APIPath
	r.fieldMap["icon"] = r.Icon
	r.fieldMap["sort_order"] = r.SortOrder
	r.fieldMap["visible"] = r.Visible
	r.fieldMap["status"] = r.Status
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r resource) clone(db *gorm.DB) resource {
	r.resourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resource) replaceDB(db *gorm.DB) resource {
	r.resourceDo.ReplaceDB(db)
	return r
}

type resourceDo struct{ gen.DO }

type IResourceDo interface {
	gen.SubQuery
	Debug() IResourceDo
	WithContext(ctx context.Context) IResourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResourceDo
	WriteDB() IResourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResourceDo
	Not(conds ...gen.Condition) IResourceDo
	Or(conds ...gen.Condition) IResourceDo
	Select(conds ...field.Expr) IResourceDo
	Where(conds ...gen.Condition) IResourceDo
	Order(conds ...field.Expr) IResourceDo
	Distinct(cols ...field.Expr) IResourceDo
	Omit(cols ...field.Expr) IResourceDo
	Join(table schema.Tabler, on ...field.Expr) IResourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResourceDo
	Group(cols ...field.Expr) IResourceDo
	Having(conds ...gen.Condition) IResourceDo
	Limit(limit int) IResourceDo
	Offset(offset int) IResourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceDo
	Unscoped() IResourceDo
	Create(values ...*model.Resource) error
	CreateInBatches(values []*model.Resource, batchSize int) error
	Save(values ...*model.Resource) error
	First() (*model.Resource, error)
	Take() (*model.Resource, error)
	Last() (*model.Resource, error)
	Find() ([]*model.Resource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Resource, err error)
	FindInBatches(result *[]*model.Resource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Resource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResourceDo
	Assign(attrs ...field.AssignExpr) IResourceDo
	Joins(fields ...field.RelationField) IResourceDo
	Preload(fields ...field.RelationField) IResourceDo
	FirstOrInit() (*model.Resource, error)
	FirstOrCreate() (*model.Resource, error)
	FindByPage(offset int, limit int) (result []*model.Resource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resourceDo) Debug() IResourceDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceDo) WithContext(ctx context.Context) IResourceDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceDo) ReadDB() IResourceDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceDo) WriteDB() IResourceDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceDo) Session(config *gorm.Session) IResourceDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceDo) Clauses(conds ...clause.Expression) IResourceDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceDo) Returning(value interface{}, columns ...string) IResourceDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceDo) Not(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceDo) Or(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceDo) Select(conds ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceDo) Where(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceDo) Order(conds ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceDo) Distinct(cols ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceDo) Omit(cols ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceDo) Join(table schema.Tabler, on ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResourceDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceDo) RightJoin(table schema.Tabler, on ...field.Expr) IResourceDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceDo) Group(cols ...field.Expr) IResourceDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceDo) Having(conds ...gen.Condition) IResourceDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceDo) Limit(limit int) IResourceDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceDo) Offset(offset int) IResourceDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceDo) Unscoped() IResourceDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceDo) Create(values ...*model.Resource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceDo) CreateInBatches(values []*model.Resource, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceDo) Save(values ...*model.Resource) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceDo) First() (*model.Resource, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) Take() (*model.Resource, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) Last() (*model.Resource, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) Find() ([]*model.Resource, error) {
	result, err := r.DO.Find()
	return result.([]*model.Resource), err
}

func (r resourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Resource, err error) {
	buf := make([]*model.Resource, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceDo) FindInBatches(result *[]*model.Resource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceDo) Attrs(attrs ...field.AssignExpr) IResourceDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceDo) Assign(attrs ...field.AssignExpr) IResourceDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceDo) Joins(fields ...field.RelationField) IResourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceDo) Preload(fields ...field.RelationField) IResourceDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceDo) FirstOrInit() (*model.Resource, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) FirstOrCreate() (*model.Resource, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resource), nil
	}
}

func (r resourceDo) FindByPage(offset int, limit int) (result []*model.Resource, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceDo) Delete(models ...*model.Resource) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceDo) withDO(do gen.Dao) *resourceDo {
	r.DO = *do.(*gen.DO)
	return r
}
