// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package worker

import (
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/sleep-go/kratos-admin/app/worker/internal/server"
	"github.com/sleep-go/kratos-admin/app/worker/internal/service"
	"github.com/sleep-go/kratos-admin/internal/conf"
	"github.com/sleep-go/kratos-admin/internal/data"
	"github.com/sleep-go/kratos-admin/internal/provider"
)

// Injectors from wire.go:

func wireApplication(ctx context.Context, cfg conf.Config) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	workerSet, err := provider.NewWorkerSet(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	logger := newLogger()
	serviceService := service.NewService(dataData, workerSet, logger)
	serverServer := server.NewServer(cfg, serviceService, logger)
	app := server.NewApp(serverServer, logger)
	return app, func() {
		cleanup()
	}, nil
}
