// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{0}
}

type GetCaptchaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	ImageDataUri  string                 `protobuf:"bytes,2,opt,name=image_data_uri,json=imageDataUri,proto3" json:"image_data_uri,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaResponse) Reset() {
	*x = GetCaptchaResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaResponse) ProtoMessage() {}

func (x *GetCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaResponse.ProtoReflect.Descriptor instead.
func (*GetCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetCaptchaResponse) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *GetCaptchaResponse) GetImageDataUri() string {
	if x != nil {
		return x.ImageDataUri
	}
	return ""
}

func (x *GetCaptchaResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type TenantSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSummary) Reset() {
	*x = TenantSummary{}
	mi := &file_admin_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSummary) ProtoMessage() {}

func (x *TenantSummary) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSummary.ProtoReflect.Descriptor instead.
func (*TenantSummary) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *TenantSummary) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CurrentUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	PlatformAdmin bool                   `protobuf:"varint,4,opt,name=platform_admin,json=platformAdmin,proto3" json:"platform_admin,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	MfaEnabled    bool                   `protobuf:"varint,9,opt,name=mfa_enabled,json=mfaEnabled,proto3" json:"mfa_enabled,omitempty"`
	MfaChannel    string                 `protobuf:"bytes,10,opt,name=mfa_channel,json=mfaChannel,proto3" json:"mfa_channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUser) Reset() {
	*x = CurrentUser{}
	mi := &file_admin_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUser) ProtoMessage() {}

func (x *CurrentUser) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUser.ProtoReflect.Descriptor instead.
func (*CurrentUser) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CurrentUser) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CurrentUser) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CurrentUser) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CurrentUser) GetPlatformAdmin() bool {
	if x != nil {
		return x.PlatformAdmin
	}
	return false
}

func (x *CurrentUser) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CurrentUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CurrentUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CurrentUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CurrentUser) GetMfaEnabled() bool {
	if x != nil {
		return x.MfaEnabled
	}
	return false
}

func (x *CurrentUser) GetMfaChannel() string {
	if x != nil {
		return x.MfaChannel
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CaptchaId     string                 `protobuf:"bytes,3,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	CaptchaCode   string                 `protobuf:"bytes,4,opt,name=captcha_code,json=captchaCode,proto3" json:"captcha_code,omitempty"`
	DeviceName    string                 `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *LoginRequest) GetCaptchaCode() string {
	if x != nil {
		return x.CaptchaCode
	}
	return ""
}

func (x *LoginRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type LoginResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	User           *CurrentUser           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Tenants        []*TenantSummary       `protobuf:"bytes,4,rep,name=tenants,proto3" json:"tenants,omitempty"`
	CurrentTenant  *TenantSummary         `protobuf:"bytes,5,opt,name=current_tenant,json=currentTenant,proto3" json:"current_tenant,omitempty"`
	MfaChallengeId string                 `protobuf:"bytes,6,opt,name=mfa_challenge_id,json=mfaChallengeId,proto3" json:"mfa_challenge_id,omitempty"`
	MfaRequired    bool                   `protobuf:"varint,7,opt,name=mfa_required,json=mfaRequired,proto3" json:"mfa_required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *LoginResponse) GetUser() *CurrentUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetTenants() []*TenantSummary {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *LoginResponse) GetCurrentTenant() *TenantSummary {
	if x != nil {
		return x.CurrentTenant
	}
	return nil
}

func (x *LoginResponse) GetMfaChallengeId() string {
	if x != nil {
		return x.MfaChallengeId
	}
	return ""
}

func (x *LoginResponse) GetMfaRequired() bool {
	if x != nil {
		return x.MfaRequired
	}
	return false
}

type VerifyMfaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMfaRequest) Reset() {
	*x = VerifyMfaRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMfaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMfaRequest) ProtoMessage() {}

func (x *VerifyMfaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMfaRequest.ProtoReflect.Descriptor instead.
func (*VerifyMfaRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyMfaRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *VerifyMfaRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyMfaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	User          *CurrentUser           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Tenants       []*TenantSummary       `protobuf:"bytes,4,rep,name=tenants,proto3" json:"tenants,omitempty"`
	CurrentTenant *TenantSummary         `protobuf:"bytes,5,opt,name=current_tenant,json=currentTenant,proto3" json:"current_tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMfaResponse) Reset() {
	*x = VerifyMfaResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMfaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMfaResponse) ProtoMessage() {}

func (x *VerifyMfaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMfaResponse.ProtoReflect.Descriptor instead.
func (*VerifyMfaResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyMfaResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyMfaResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *VerifyMfaResponse) GetUser() *CurrentUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *VerifyMfaResponse) GetTenants() []*TenantSummary {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *VerifyMfaResponse) GetCurrentTenant() *TenantSummary {
	if x != nil {
		return x.CurrentTenant
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{8}
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	User          *CurrentUser           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Tenants       []*TenantSummary       `protobuf:"bytes,4,rep,name=tenants,proto3" json:"tenants,omitempty"`
	CurrentTenant *TenantSummary         `protobuf:"bytes,5,opt,name=current_tenant,json=currentTenant,proto3" json:"current_tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RefreshResponse) GetUser() *CurrentUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RefreshResponse) GetTenants() []*TenantSummary {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *RefreshResponse) GetCurrentTenant() *TenantSummary {
	if x != nil {
		return x.CurrentTenant
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{10}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{11}
}

type SwitchTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchTenantRequest) Reset() {
	*x = SwitchTenantRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchTenantRequest) ProtoMessage() {}

func (x *SwitchTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchTenantRequest.ProtoReflect.Descriptor instead.
func (*SwitchTenantRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *SwitchTenantRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type SwitchTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CurrentTenant *TenantSummary         `protobuf:"bytes,3,opt,name=current_tenant,json=currentTenant,proto3" json:"current_tenant,omitempty"`
	User          *CurrentUser           `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Tenants       []*TenantSummary       `protobuf:"bytes,5,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchTenantResponse) Reset() {
	*x = SwitchTenantResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchTenantResponse) ProtoMessage() {}

func (x *SwitchTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchTenantResponse.ProtoReflect.Descriptor instead.
func (*SwitchTenantResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *SwitchTenantResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SwitchTenantResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SwitchTenantResponse) GetCurrentTenant() *TenantSummary {
	if x != nil {
		return x.CurrentTenant
	}
	return nil
}

func (x *SwitchTenantResponse) GetUser() *CurrentUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SwitchTenantResponse) GetTenants() []*TenantSummary {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ForgotPasswordRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ForgotPasswordRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ForgotPasswordResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ForgotPasswordResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ResetPasswordRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ResetPasswordRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{17}
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Current       bool                   `protobuf:"varint,8,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_admin_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Session) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Session) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Session) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{19}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Session             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{20}
}

func (x *ListSessionsResponse) GetItems() []*Session {
	if x != nil {
		return x.Items
	}
	return nil
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *RevokeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{22}
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *CurrentUser           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateProfileResponse) GetUser() *CurrentUser {
	if x != nil {
		return x.User
	}
	return nil
}

type NavigationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      uint64                 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	RoutePath     string                 `protobuf:"bytes,5,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	ComponentKey  string                 `protobuf:"bytes,6,opt,name=component_key,json=componentKey,proto3" json:"component_key,omitempty"`
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	SortOrder     uint32                 `protobuf:"varint,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigationItem) Reset() {
	*x = NavigationItem{}
	mi := &file_admin_v1_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationItem) ProtoMessage() {}

func (x *NavigationItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationItem.ProtoReflect.Descriptor instead.
func (*NavigationItem) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{25}
}

func (x *NavigationItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NavigationItem) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *NavigationItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NavigationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NavigationItem) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *NavigationItem) GetComponentKey() string {
	if x != nil {
		return x.ComponentKey
	}
	return ""
}

func (x *NavigationItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *NavigationItem) GetSortOrder() uint32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ListNavigationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNavigationRequest) Reset() {
	*x = ListNavigationRequest{}
	mi := &file_admin_v1_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNavigationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNavigationRequest) ProtoMessage() {}

func (x *ListNavigationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNavigationRequest.ProtoReflect.Descriptor instead.
func (*ListNavigationRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{26}
}

type ListNavigationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*NavigationItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNavigationResponse) Reset() {
	*x = ListNavigationResponse{}
	mi := &file_admin_v1_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNavigationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNavigationResponse) ProtoMessage() {}

func (x *ListNavigationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNavigationResponse.ProtoReflect.Descriptor instead.
func (*ListNavigationResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_auth_proto_rawDescGZIP(), []int{27}
}

func (x *ListNavigationResponse) GetItems() []*NavigationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_admin_v1_auth_proto protoreflect.FileDescriptor

const file_admin_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x13admin/v1/auth.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n" +
	"\x11GetCaptchaRequest\"\x94\x01\n" +
	"\x12GetCaptchaResponse\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tR\tcaptchaId\x12$\n" +
	"\x0eimage_data_uri\x18\x02 \x01(\tR\fimageDataUri\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"3\n" +
	"\rTenantSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb2\x02\n" +
	"\vCurrentUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12%\n" +
	"\x0eplatform_admin\x18\x04 \x01(\bR\rplatformAdmin\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x1f\n" +
	"\vmfa_enabled\x18\t \x01(\bR\n" +
	"mfaEnabled\x12\x1f\n" +
	"\vmfa_channel\x18\n" +
	" \x01(\tR\n" +
	"mfaChannel\"\xad\x01\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x03 \x01(\tR\tcaptchaId\x12!\n" +
	"\fcaptcha_code\x18\x04 \x01(\tR\vcaptchaCode\x12\x1f\n" +
	"\vdevice_name\x18\x05 \x01(\tR\n" +
	"deviceName\"\xd8\x02\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12)\n" +
	"\x04user\x18\x03 \x01(\v2\x15.admin.v1.CurrentUserR\x04user\x121\n" +
	"\atenants\x18\x04 \x03(\v2\x17.admin.v1.TenantSummaryR\atenants\x12>\n" +
	"\x0ecurrent_tenant\x18\x05 \x01(\v2\x17.admin.v1.TenantSummaryR\rcurrentTenant\x12(\n" +
	"\x10mfa_challenge_id\x18\x06 \x01(\tR\x0emfaChallengeId\x12!\n" +
	"\fmfa_required\x18\a \x01(\bR\vmfaRequired\"I\n" +
	"\x10VerifyMfaRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x8f\x02\n" +
	"\x11VerifyMfaResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12)\n" +
	"\x04user\x18\x03 \x01(\v2\x15.admin.v1.CurrentUserR\x04user\x121\n" +
	"\atenants\x18\x04 \x03(\v2\x17.admin.v1.TenantSummaryR\atenants\x12>\n" +
	"\x0ecurrent_tenant\x18\x05 \x01(\v2\x17.admin.v1.TenantSummaryR\rcurrentTenant\"\x10\n" +
	"\x0eRefreshRequest\"\x8d\x02\n" +
	"\x0fRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12)\n" +
	"\x04user\x18\x03 \x01(\v2\x15.admin.v1.CurrentUserR\x04user\x121\n" +
	"\atenants\x18\x04 \x03(\v2\x17.admin.v1.TenantSummaryR\atenants\x12>\n" +
	"\x0ecurrent_tenant\x18\x05 \x01(\v2\x17.admin.v1.TenantSummaryR\rcurrentTenant\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"2\n" +
	"\x13SwitchTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\"\x92\x02\n" +
	"\x14SwitchTenantResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12>\n" +
	"\x0ecurrent_tenant\x18\x03 \x01(\v2\x17.admin.v1.TenantSummaryR\rcurrentTenant\x12)\n" +
	"\x04user\x18\x04 \x01(\v2\x15.admin.v1.CurrentUserR\x04user\x121\n" +
	"\atenants\x18\x05 \x03(\v2\x17.admin.v1.TenantSummaryR\atenants\"Q\n" +
	"\x15ForgotPasswordRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"v\n" +
	"\x16ForgotPasswordResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"p\n" +
	"\x14ResetPasswordRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"\x17\n" +
	"\x15ResetPasswordResponse\"\x96\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\acurrent\x18\b \x01(\bR\acurrent\"\x15\n" +
	"\x13ListSessionsRequest\"?\n" +
	"\x14ListSessionsResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.admin.v1.SessionR\x05items\"5\n" +
	"\x14RevokeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15RevokeSessionResponse\"\x84\x01\n" +
	"\x14UpdateProfileRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"B\n" +
	"\x15UpdateProfileResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.admin.v1.CurrentUserR\x04user\"\xdc\x01\n" +
	"\x0eNavigationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x04R\bparentId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"route_path\x18\x05 \x01(\tR\troutePath\x12#\n" +
	"\rcomponent_key\x18\x06 \x01(\tR\fcomponentKey\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\rR\tsortOrder\"\x17\n" +
	"\x15ListNavigationRequest\"H\n" +
	"\x16ListNavigationResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.admin.v1.NavigationItemR\x05items2\xb5\n" +
	"\n" +
	"\vAuthService\x12e\n" +
	"\n" +
	"GetCaptcha\x12\x1b.admin.v1.GetCaptchaRequest\x1a\x1c.admin.v1.GetCaptchaResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/auth/captcha\x12W\n" +
	"\x05Login\x12\x16.admin.v1.LoginRequest\x1a\x17.admin.v1.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12h\n" +
	"\tVerifyMfa\x12\x1a.admin.v1.VerifyMfaRequest\x1a\x1b.admin.v1.VerifyMfaResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/auth/mfa/verify\x12_\n" +
	"\aRefresh\x12\x18.admin.v1.RefreshRequest\x1a\x19.admin.v1.RefreshResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12X\n" +
	"\x06Logout\x12\x17.admin.v1.LogoutRequest\x1a\x18.admin.v1.LogoutResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/api/v1/auth/logout\x12t\n" +
	"\fSwitchTenant\x12\x1d.admin.v1.SwitchTenantRequest\x1a\x1e.admin.v1.SwitchTenantResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/auth/switch-tenant\x12|\n" +
	"\x0eForgotPassword\x12\x1f.admin.v1.ForgotPasswordRequest\x1a .admin.v1.ForgotPasswordResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/auth/forgot-password\x12x\n" +
	"\rResetPassword\x12\x1e.admin.v1.ResetPasswordRequest\x1a\x1f.admin.v1.ResetPasswordResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/auth/reset-password\x12l\n" +
	"\fListSessions\x12\x1d.admin.v1.ListSessionsRequest\x1a\x1e.admin.v1.ListSessionsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/auth/sessions\x12|\n" +
	"\rRevokeSession\x12\x1e.admin.v1.RevokeSessionRequest\x1a\x1f.admin.v1.RevokeSessionResponse\"*\x82\xd3\xe4\x93\x02$*\"/api/v1/auth/sessions/{session_id}\x12q\n" +
	"\rUpdateProfile\x12\x1e.admin.v1.UpdateProfileRequest\x1a\x1f.admin.v1.UpdateProfileResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/v1/auth/profile\x12t\n" +
	"\x0eListNavigation\x12\x1f.admin.v1.ListNavigationRequest\x1a .admin.v1.ListNavigationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/auth/navigationB2Z0github.com/sleep-go/kratos-admin/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_auth_proto_rawDescOnce sync.Once
	file_admin_v1_auth_proto_rawDescData []byte
)

func file_admin_v1_auth_proto_rawDescGZIP() []byte {
	file_admin_v1_auth_proto_rawDescOnce.Do(func() {
		file_admin_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_auth_proto_rawDesc), len(file_admin_v1_auth_proto_rawDesc)))
	})
	return file_admin_v1_auth_proto_rawDescData
}

var file_admin_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_admin_v1_auth_proto_goTypes = []any{
	(*GetCaptchaRequest)(nil),      // 0: admin.v1.GetCaptchaRequest
	(*GetCaptchaResponse)(nil),     // 1: admin.v1.GetCaptchaResponse
	(*TenantSummary)(nil),          // 2: admin.v1.TenantSummary
	(*CurrentUser)(nil),            // 3: admin.v1.CurrentUser
	(*LoginRequest)(nil),           // 4: admin.v1.LoginRequest
	(*LoginResponse)(nil),          // 5: admin.v1.LoginResponse
	(*VerifyMfaRequest)(nil),       // 6: admin.v1.VerifyMfaRequest
	(*VerifyMfaResponse)(nil),      // 7: admin.v1.VerifyMfaResponse
	(*RefreshRequest)(nil),         // 8: admin.v1.RefreshRequest
	(*RefreshResponse)(nil),        // 9: admin.v1.RefreshResponse
	(*LogoutRequest)(nil),          // 10: admin.v1.LogoutRequest
	(*LogoutResponse)(nil),         // 11: admin.v1.LogoutResponse
	(*SwitchTenantRequest)(nil),    // 12: admin.v1.SwitchTenantRequest
	(*SwitchTenantResponse)(nil),   // 13: admin.v1.SwitchTenantResponse
	(*ForgotPasswordRequest)(nil),  // 14: admin.v1.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil), // 15: admin.v1.ForgotPasswordResponse
	(*ResetPasswordRequest)(nil),   // 16: admin.v1.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),  // 17: admin.v1.ResetPasswordResponse
	(*Session)(nil),                // 18: admin.v1.Session
	(*ListSessionsRequest)(nil),    // 19: admin.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 20: admin.v1.ListSessionsResponse
	(*RevokeSessionRequest)(nil),   // 21: admin.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),  // 22: admin.v1.RevokeSessionResponse
	(*UpdateProfileRequest)(nil),   // 23: admin.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),  // 24: admin.v1.UpdateProfileResponse
	(*NavigationItem)(nil),         // 25: admin.v1.NavigationItem
	(*ListNavigationRequest)(nil),  // 26: admin.v1.ListNavigationRequest
	(*ListNavigationResponse)(nil), // 27: admin.v1.ListNavigationResponse
	(*timestamppb.Timestamp)(nil),  // 28: google.protobuf.Timestamp
}
var file_admin_v1_auth_proto_depIdxs = []int32{
	28, // 0: admin.v1.GetCaptchaResponse.expires_at:type_name -> google.protobuf.Timestamp
	28, // 1: admin.v1.LoginResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 2: admin.v1.LoginResponse.user:type_name -> admin.v1.CurrentUser
	2,  // 3: admin.v1.LoginResponse.tenants:type_name -> admin.v1.TenantSummary
	2,  // 4: admin.v1.LoginResponse.current_tenant:type_name -> admin.v1.TenantSummary
	28, // 5: admin.v1.VerifyMfaResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 6: admin.v1.VerifyMfaResponse.user:type_name -> admin.v1.CurrentUser
	2,  // 7: admin.v1.VerifyMfaResponse.tenants:type_name -> admin.v1.TenantSummary
	2,  // 8: admin.v1.VerifyMfaResponse.current_tenant:type_name -> admin.v1.TenantSummary
	28, // 9: admin.v1.RefreshResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 10: admin.v1.RefreshResponse.user:type_name -> admin.v1.CurrentUser
	2,  // 11: admin.v1.RefreshResponse.tenants:type_name -> admin.v1.TenantSummary
	2,  // 12: admin.v1.RefreshResponse.current_tenant:type_name -> admin.v1.TenantSummary
	28, // 13: admin.v1.SwitchTenantResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 14: admin.v1.SwitchTenantResponse.current_tenant:type_name -> admin.v1.TenantSummary
	3,  // 15: admin.v1.SwitchTenantResponse.user:type_name -> admin.v1.CurrentUser
	2,  // 16: admin.v1.SwitchTenantResponse.tenants:type_name -> admin.v1.TenantSummary
	28, // 17: admin.v1.ForgotPasswordResponse.expires_at:type_name -> google.protobuf.Timestamp
	28, // 18: admin.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	28, // 19: admin.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	18, // 20: admin.v1.ListSessionsResponse.items:type_name -> admin.v1.Session
	3,  // 21: admin.v1.UpdateProfileResponse.user:type_name -> admin.v1.CurrentUser
	25, // 22: admin.v1.ListNavigationResponse.items:type_name -> admin.v1.NavigationItem
	0,  // 23: admin.v1.AuthService.GetCaptcha:input_type -> admin.v1.GetCaptchaRequest
	4,  // 24: admin.v1.AuthService.Login:input_type -> admin.v1.LoginRequest
	6,  // 25: admin.v1.AuthService.VerifyMfa:input_type -> admin.v1.VerifyMfaRequest
	8,  // 26: admin.v1.AuthService.Refresh:input_type -> admin.v1.RefreshRequest
	10, // 27: admin.v1.AuthService.Logout:input_type -> admin.v1.LogoutRequest
	12, // 28: admin.v1.AuthService.SwitchTenant:input_type -> admin.v1.SwitchTenantRequest
	14, // 29: admin.v1.AuthService.ForgotPassword:input_type -> admin.v1.ForgotPasswordRequest
	16, // 30: admin.v1.AuthService.ResetPassword:input_type -> admin.v1.ResetPasswordRequest
	19, // 31: admin.v1.AuthService.ListSessions:input_type -> admin.v1.ListSessionsRequest
	21, // 32: admin.v1.AuthService.RevokeSession:input_type -> admin.v1.RevokeSessionRequest
	23, // 33: admin.v1.AuthService.UpdateProfile:input_type -> admin.v1.UpdateProfileRequest
	26, // 34: admin.v1.AuthService.ListNavigation:input_type -> admin.v1.ListNavigationRequest
	1,  // 35: admin.v1.AuthService.GetCaptcha:output_type -> admin.v1.GetCaptchaResponse
	5,  // 36: admin.v1.AuthService.Login:output_type -> admin.v1.LoginResponse
	7,  // 37: admin.v1.AuthService.VerifyMfa:output_type -> admin.v1.VerifyMfaResponse
	9,  // 38: admin.v1.AuthService.Refresh:output_type -> admin.v1.RefreshResponse
	11, // 39: admin.v1.AuthService.Logout:output_type -> admin.v1.LogoutResponse
	13, // 40: admin.v1.AuthService.SwitchTenant:output_type -> admin.v1.SwitchTenantResponse
	15, // 41: admin.v1.AuthService.ForgotPassword:output_type -> admin.v1.ForgotPasswordResponse
	17, // 42: admin.v1.AuthService.ResetPassword:output_type -> admin.v1.ResetPasswordResponse
	20, // 43: admin.v1.AuthService.ListSessions:output_type -> admin.v1.ListSessionsResponse
	22, // 44: admin.v1.AuthService.RevokeSession:output_type -> admin.v1.RevokeSessionResponse
	24, // 45: admin.v1.AuthService.UpdateProfile:output_type -> admin.v1.UpdateProfileResponse
	27, // 46: admin.v1.AuthService.ListNavigation:output_type -> admin.v1.ListNavigationResponse
	35, // [35:47] is the sub-list for method output_type
	23, // [23:35] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_admin_v1_auth_proto_init() }
func file_admin_v1_auth_proto_init() {
	if File_admin_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_auth_proto_rawDesc), len(file_admin_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_auth_proto_goTypes,
		DependencyIndexes: file_admin_v1_auth_proto_depIdxs,
		MessageInfos:      file_admin_v1_auth_proto_msgTypes,
	}.Build()
	File_admin_v1_auth_proto = out.File
	file_admin_v1_auth_proto_goTypes = nil
	file_admin_v1_auth_proto_depIdxs = nil
}
