// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/file.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalName  string                 `protobuf:"bytes,1,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadRequest) Reset() {
	*x = CreateUploadRequest{}
	mi := &file_admin_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadRequest) ProtoMessage() {}

func (x *CreateUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUploadRequest) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *CreateUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateUploadRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateUploadRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type SignedFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedFileRequest) Reset() {
	*x = SignedFileRequest{}
	mi := &file_admin_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedFileRequest) ProtoMessage() {}

func (x *SignedFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedFileRequest.ProtoReflect.Descriptor instead.
func (*SignedFileRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *SignedFileRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SignedFileRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SignedFileRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SignedFileRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ProviderName  string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Upload        *SignedFileRequest     `protobuf:"bytes,4,opt,name=upload,proto3" json:"upload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadResponse) Reset() {
	*x = CreateUploadResponse{}
	mi := &file_admin_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadResponse) ProtoMessage() {}

func (x *CreateUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CreateUploadResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *CreateUploadResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *CreateUploadResponse) GetUpload() *SignedFileRequest {
	if x != nil {
		return x.Upload
	}
	return nil
}

type ConfirmUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_admin_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_file_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmUploadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type ConfirmUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderName  string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	OriginalName  string                 `protobuf:"bytes,4,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Status        uint32                 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUploadResponse) Reset() {
	*x = ConfirmUploadResponse{}
	mi := &file_admin_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadResponse) ProtoMessage() {}

func (x *ConfirmUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUploadResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_file_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmUploadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmUploadResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ConfirmUploadResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ConfirmUploadResponse) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *ConfirmUploadResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfirmUploadResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ConfirmUploadResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ConfirmUploadResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ConfirmUploadResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Download      *SignedFileRequest     `protobuf:"bytes,1,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLResponse) Reset() {
	*x = GetDownloadURLResponse{}
	mi := &file_admin_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLResponse) ProtoMessage() {}

func (x *GetDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_file_proto_rawDescGZIP(), []int{5}
}

func (x *GetDownloadURLResponse) GetDownload() *SignedFileRequest {
	if x != nil {
		return x.Download
	}
	return nil
}

type GetDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadURLRequest) Reset() {
	*x = GetDownloadURLRequest{}
	mi := &file_admin_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadURLRequest) ProtoMessage() {}

func (x *GetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetDownloadURLRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_admin_v1_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_file_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_admin_v1_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_file_proto_rawDescGZIP(), []int{8}
}

var File_admin_v1_file_proto protoreflect.FileDescriptor

const file_admin_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x13admin/v1/file.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x01\n" +
	"\x13CreateUploadRequest\x12#\n" +
	"\roriginal_name\x18\x01 \x01(\tR\foriginalName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"\xf8\x01\n" +
	"\x11SignedFileRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12B\n" +
	"\aheaders\x18\x03 \x03(\v2(.admin.v1.SignedFileRequest.HeadersEntryR\aheaders\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\x14CreateUploadResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x123\n" +
	"\x06upload\x18\x04 \x01(\v2\x1b.admin.v1.SignedFileRequestR\x06upload\"/\n" +
	"\x14ConfirmUploadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\xbd\x02\n" +
	"\x15ConfirmUploadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\x12#\n" +
	"\roriginal_name\x18\x04 \x01(\tR\foriginalName\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256\x12\x16\n" +
	"\x06status\x18\b \x01(\rR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"Q\n" +
	"\x16GetDownloadURLResponse\x127\n" +
	"\bdownload\x18\x01 \x01(\v2\x1b.admin.v1.SignedFileRequestR\bdownload\"0\n" +
	"\x15GetDownloadURLRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\",\n" +
	"\x11DeleteFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x14\n" +
	"\x12DeleteFileResponse2\xea\x03\n" +
	"\vFileService\x12o\n" +
	"\fCreateUpload\x12\x1d.admin.v1.CreateUploadRequest\x1a\x1e.admin.v1.CreateUploadResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/files/uploads\x12|\n" +
	"\rConfirmUpload\x12\x1e.admin.v1.ConfirmUploadRequest\x1a\x1f.admin.v1.ConfirmUploadResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/files/{file_id}/confirm\x12\x81\x01\n" +
	"\x0eGetDownloadURL\x12\x1f.admin.v1.GetDownloadURLRequest\x1a .admin.v1.GetDownloadURLResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/files/{file_id}/download-url\x12h\n" +
	"\n" +
	"DeleteFile\x12\x1b.admin.v1.DeleteFileRequest\x1a\x1c.admin.v1.DeleteFileResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/files/{file_id}B2Z0github.com/sleep-go/kratos-admin/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_file_proto_rawDescOnce sync.Once
	file_admin_v1_file_proto_rawDescData []byte
)

func file_admin_v1_file_proto_rawDescGZIP() []byte {
	file_admin_v1_file_proto_rawDescOnce.Do(func() {
		file_admin_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_file_proto_rawDesc), len(file_admin_v1_file_proto_rawDesc)))
	})
	return file_admin_v1_file_proto_rawDescData
}

var file_admin_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_admin_v1_file_proto_goTypes = []any{
	(*CreateUploadRequest)(nil),    // 0: admin.v1.CreateUploadRequest
	(*SignedFileRequest)(nil),      // 1: admin.v1.SignedFileRequest
	(*CreateUploadResponse)(nil),   // 2: admin.v1.CreateUploadResponse
	(*ConfirmUploadRequest)(nil),   // 3: admin.v1.ConfirmUploadRequest
	(*ConfirmUploadResponse)(nil),  // 4: admin.v1.ConfirmUploadResponse
	(*GetDownloadURLResponse)(nil), // 5: admin.v1.GetDownloadURLResponse
	(*GetDownloadURLRequest)(nil),  // 6: admin.v1.GetDownloadURLRequest
	(*DeleteFileRequest)(nil),      // 7: admin.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),     // 8: admin.v1.DeleteFileResponse
	nil,                            // 9: admin.v1.SignedFileRequest.HeadersEntry
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_admin_v1_file_proto_depIdxs = []int32{
	9,  // 0: admin.v1.SignedFileRequest.headers:type_name -> admin.v1.SignedFileRequest.HeadersEntry
	10, // 1: admin.v1.SignedFileRequest.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 2: admin.v1.CreateUploadResponse.upload:type_name -> admin.v1.SignedFileRequest
	10, // 3: admin.v1.ConfirmUploadResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: admin.v1.GetDownloadURLResponse.download:type_name -> admin.v1.SignedFileRequest
	0,  // 5: admin.v1.FileService.CreateUpload:input_type -> admin.v1.CreateUploadRequest
	3,  // 6: admin.v1.FileService.ConfirmUpload:input_type -> admin.v1.ConfirmUploadRequest
	6,  // 7: admin.v1.FileService.GetDownloadURL:input_type -> admin.v1.GetDownloadURLRequest
	7,  // 8: admin.v1.FileService.DeleteFile:input_type -> admin.v1.DeleteFileRequest
	2,  // 9: admin.v1.FileService.CreateUpload:output_type -> admin.v1.CreateUploadResponse
	4,  // 10: admin.v1.FileService.ConfirmUpload:output_type -> admin.v1.ConfirmUploadResponse
	5,  // 11: admin.v1.FileService.GetDownloadURL:output_type -> admin.v1.GetDownloadURLResponse
	8,  // 12: admin.v1.FileService.DeleteFile:output_type -> admin.v1.DeleteFileResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_admin_v1_file_proto_init() }
func file_admin_v1_file_proto_init() {
	if File_admin_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_file_proto_rawDesc), len(file_admin_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_file_proto_goTypes,
		DependencyIndexes: file_admin_v1_file_proto_depIdxs,
		MessageInfos:      file_admin_v1_file_proto_msgTypes,
	}.Build()
	File_admin_v1_file_proto = out.File
	file_admin_v1_file_proto_goTypes = nil
	file_admin_v1_file_proto_depIdxs = nil
}
