// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: admin/v1/health.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHealthServiceCheck = "/admin.v1.HealthService/Check"

type HealthServiceHTTPServer interface {
	// Check Check 返回 API 进程当前健康状态。
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
}

func RegisterHealthServiceHTTPServer(s *http.Server, srv HealthServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/health", _HealthService_Check0_HTTP_Handler(srv))
}

func _HealthService_Check0_HTTP_Handler(srv HealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthServiceCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Check(ctx, req.(*CheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckResponse)
		return ctx.Result(200, reply)
	}
}

type HealthServiceHTTPClient interface {
	// Check Check 返回 API 进程当前健康状态。
	Check(ctx context.Context, req *CheckRequest, opts ...http.CallOption) (rsp *CheckResponse, err error)
}

type HealthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthServiceHTTPClient(client *http.Client) HealthServiceHTTPClient {
	return &HealthServiceHTTPClientImpl{client}
}

// Check Check 返回 API 进程当前健康状态。
func (c *HealthServiceHTTPClientImpl) Check(ctx context.Context, in *CheckRequest, opts ...http.CallOption) (*CheckResponse, error) {
	var out CheckResponse
	pattern := "/api/v1/health"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthServiceCheck))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
