// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/management.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListResourcesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Resource       string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Page           uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword        string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Sort           string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Filters        map[string]string      `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TargetTenantId uint64                 `protobuf:"varint,7,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_admin_v1_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{0}
}

func (x *ListResourcesRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ListResourcesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResourcesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListResourcesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListResourcesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListResourcesRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListResourcesRequest) GetTargetTenantId() uint64 {
	if x != nil {
		return x.TargetTenantId
	}
	return 0
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*structpb.Struct     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_admin_v1_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{1}
}

func (x *ListResourcesResponse) GetItems() []*structpb.Struct {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListResourcesResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListResourcesResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResourcesResponse) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Resource       string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Data           *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TargetTenantId uint64                 `protobuf:"varint,3,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_admin_v1_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResourceRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CreateResourceRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateResourceRequest) GetTargetTenantId() uint64 {
	if x != nil {
		return x.TargetTenantId
	}
	return 0
}

type UpdateResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Resource       string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Id             uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data           *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	TargetTenantId uint64                 `protobuf:"varint,4,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_admin_v1_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResourceRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *UpdateResourceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateResourceRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateResourceRequest) GetTargetTenantId() uint64 {
	if x != nil {
		return x.TargetTenantId
	}
	return 0
}

type DeleteResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Resource       string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Id             uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	TargetTenantId uint64                 `protobuf:"varint,3,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_admin_v1_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteResourceRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *DeleteResourceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteResourceRequest) GetTargetTenantId() uint64 {
	if x != nil {
		return x.TargetTenantId
	}
	return 0
}

type CreateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	mi := &file_admin_v1_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResourceResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceResponse) Reset() {
	*x = UpdateResourceResponse{}
	mi := &file_admin_v1_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceResponse) ProtoMessage() {}

func (x *UpdateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceResponse.ProtoReflect.Descriptor instead.
func (*UpdateResourceResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResourceResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_admin_v1_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResourceResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEffectiveSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEffectiveSettingsRequest) Reset() {
	*x = GetEffectiveSettingsRequest{}
	mi := &file_admin_v1_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectiveSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectiveSettingsRequest) ProtoMessage() {}

func (x *GetEffectiveSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectiveSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetEffectiveSettingsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{8}
}

func (x *GetEffectiveSettingsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetEffectiveSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*structpb.Struct     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEffectiveSettingsResponse) Reset() {
	*x = GetEffectiveSettingsResponse{}
	mi := &file_admin_v1_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectiveSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectiveSettingsResponse) ProtoMessage() {}

func (x *GetEffectiveSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectiveSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetEffectiveSettingsResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{9}
}

func (x *GetEffectiveSettingsResponse) GetItems() []*structpb.Struct {
	if x != nil {
		return x.Items
	}
	return nil
}

type TestProviderConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProviderConnectionRequest) Reset() {
	*x = TestProviderConnectionRequest{}
	mi := &file_admin_v1_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderConnectionRequest) ProtoMessage() {}

func (x *TestProviderConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestProviderConnectionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{10}
}

func (x *TestProviderConnectionRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TestProviderConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProviderConnectionResponse) Reset() {
	*x = TestProviderConnectionResponse{}
	mi := &file_admin_v1_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderConnectionResponse) ProtoMessage() {}

func (x *TestProviderConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestProviderConnectionResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{11}
}

func (x *TestProviderConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestProviderConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoleResourceGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceCode  string                 `protobuf:"bytes,1,opt,name=resource_code,json=resourceCode,proto3" json:"resource_code,omitempty"`
	Actions       []string               `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResourceGrant) Reset() {
	*x = RoleResourceGrant{}
	mi := &file_admin_v1_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResourceGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResourceGrant) ProtoMessage() {}

func (x *RoleResourceGrant) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResourceGrant.ProtoReflect.Descriptor instead.
func (*RoleResourceGrant) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{12}
}

func (x *RoleResourceGrant) GetResourceCode() string {
	if x != nil {
		return x.ResourceCode
	}
	return ""
}

func (x *RoleResourceGrant) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

type UpdateRoleAuthorizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoleId         uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	DataScope      uint32                 `protobuf:"varint,2,opt,name=data_scope,json=dataScope,proto3" json:"data_scope,omitempty"`
	Grants         []*RoleResourceGrant   `protobuf:"bytes,3,rep,name=grants,proto3" json:"grants,omitempty"`
	DepartmentIds  []uint64               `protobuf:"varint,4,rep,packed,name=department_ids,json=departmentIds,proto3" json:"department_ids,omitempty"`
	TargetTenantId uint64                 `protobuf:"varint,5,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRoleAuthorizationRequest) Reset() {
	*x = UpdateRoleAuthorizationRequest{}
	mi := &file_admin_v1_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleAuthorizationRequest) ProtoMessage() {}

func (x *UpdateRoleAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRoleAuthorizationRequest) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UpdateRoleAuthorizationRequest) GetDataScope() uint32 {
	if x != nil {
		return x.DataScope
	}
	return 0
}

func (x *UpdateRoleAuthorizationRequest) GetGrants() []*RoleResourceGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *UpdateRoleAuthorizationRequest) GetDepartmentIds() []uint64 {
	if x != nil {
		return x.DepartmentIds
	}
	return nil
}

func (x *UpdateRoleAuthorizationRequest) GetTargetTenantId() uint64 {
	if x != nil {
		return x.TargetTenantId
	}
	return 0
}

type UpdateRoleAuthorizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleAuthorizationResponse) Reset() {
	*x = UpdateRoleAuthorizationResponse{}
	mi := &file_admin_v1_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleAuthorizationResponse) ProtoMessage() {}

func (x *UpdateRoleAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateRoleAuthorizationResponse) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UpdateTenantFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ResourceIds   []uint64               `protobuf:"varint,2,rep,packed,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantFeaturesRequest) Reset() {
	*x = UpdateTenantFeaturesRequest{}
	mi := &file_admin_v1_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantFeaturesRequest) ProtoMessage() {}

func (x *UpdateTenantFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantFeaturesRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTenantFeaturesRequest) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UpdateTenantFeaturesRequest) GetResourceIds() []uint64 {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

type UpdateTenantFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      uint64                 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantFeaturesResponse) Reset() {
	*x = UpdateTenantFeaturesResponse{}
	mi := &file_admin_v1_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantFeaturesResponse) ProtoMessage() {}

func (x *UpdateTenantFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantFeaturesResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_management_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateTenantFeaturesResponse) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

var File_admin_v1_management_proto protoreflect.FileDescriptor

const file_admin_v1_management_proto_rawDesc = "" +
	"\n" +
	"\x19admin/v1/management.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xbe\x02\n" +
	"\x14ListResourcesRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\x12E\n" +
	"\afilters\x18\x06 \x03(\v2+.admin.v1.ListResourcesRequest.FiltersEntryR\afilters\x12(\n" +
	"\x10target_tenant_id\x18\a \x01(\x04R\x0etargetTenantId\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x15ListResourcesResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.google.protobuf.StructR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"\x8a\x01\n" +
	"\x15CreateResourceRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12(\n" +
	"\x10target_tenant_id\x18\x03 \x01(\x04R\x0etargetTenantId\"\x9a\x01\n" +
	"\x15UpdateResourceRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12(\n" +
	"\x10target_tenant_id\x18\x04 \x01(\x04R\x0etargetTenantId\"m\n" +
	"\x15DeleteResourceRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12(\n" +
	"\x10target_tenant_id\x18\x03 \x01(\x04R\x0etargetTenantId\"(\n" +
	"\x16CreateResourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"(\n" +
	"\x16UpdateResourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"(\n" +
	"\x16DeleteResourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"9\n" +
	"\x1bGetEffectiveSettingsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"M\n" +
	"\x1cGetEffectiveSettingsResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.google.protobuf.StructR\x05items\"/\n" +
	"\x1dTestProviderConnectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"T\n" +
	"\x1eTestProviderConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x11RoleResourceGrant\x12#\n" +
	"\rresource_code\x18\x01 \x01(\tR\fresourceCode\x12\x18\n" +
	"\aactions\x18\x02 \x03(\tR\aactions\"\xde\x01\n" +
	"\x1eUpdateRoleAuthorizationRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x12\x1d\n" +
	"\n" +
	"data_scope\x18\x02 \x01(\rR\tdataScope\x123\n" +
	"\x06grants\x18\x03 \x03(\v2\x1b.admin.v1.RoleResourceGrantR\x06grants\x12%\n" +
	"\x0edepartment_ids\x18\x04 \x03(\x04R\rdepartmentIds\x12(\n" +
	"\x10target_tenant_id\x18\x05 \x01(\x04R\x0etargetTenantId\":\n" +
	"\x1fUpdateRoleAuthorizationResponse\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\"]\n" +
	"\x1bUpdateTenantFeaturesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\x04R\vresourceIds\";\n" +
	"\x1cUpdateTenantFeaturesResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x04R\btenantId2\x9f\t\n" +
	"\x11ManagementService\x12w\n" +
	"\rListResources\x12\x1e.admin.v1.ListResourcesRequest\x1a\x1f.admin.v1.ListResourcesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/management/{resource}\x12\x80\x01\n" +
	"\x0eCreateResource\x12\x1f.admin.v1.CreateResourceRequest\x1a .admin.v1.CreateResourceResponse\"+\x82\xd3\xe4\x93\x02%:\x04data\"\x1d/api/v1/management/{resource}\x12\x85\x01\n" +
	"\x0eUpdateResource\x12\x1f.admin.v1.UpdateResourceRequest\x1a .admin.v1.UpdateResourceResponse\"0\x82\xd3\xe4\x93\x02*:\x04data\x1a\"/api/v1/management/{resource}/{id}\x12\x7f\n" +
	"\x0eDeleteResource\x12\x1f.admin.v1.DeleteResourceRequest\x1a .admin.v1.DeleteResourceResponse\"*\x82\xd3\xe4\x93\x02$*\"/api/v1/management/{resource}/{id}\x12\x89\x01\n" +
	"\x14GetEffectiveSettings\x12%.admin.v1.GetEffectiveSettingsRequest\x1a&.admin.v1.GetEffectiveSettingsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/settings/effective\x12\xa6\x01\n" +
	"\x16TestProviderConnection\x12'.admin.v1.TestProviderConnectionRequest\x1a(.admin.v1.TestProviderConnectionResponse\"9\x82\xd3\xe4\x93\x023\"1/api/v1/management/providers/{id}/connection-test\x12\xab\x01\n" +
	"\x17UpdateRoleAuthorization\x12(.admin.v1.UpdateRoleAuthorizationRequest\x1a).admin.v1.UpdateRoleAuthorizationResponse\";\x82\xd3\xe4\x93\x025:\x01*\x1a0/api/v1/management/roles/{role_id}/authorization\x12\xa1\x01\n" +
	"\x14UpdateTenantFeatures\x12%.admin.v1.UpdateTenantFeaturesRequest\x1a&.admin.v1.UpdateTenantFeaturesResponse\":\x82\xd3\xe4\x93\x024:\x01*\x1a//api/v1/management/tenants/{tenant_id}/featuresB2Z0github.com/sleep-go/kratos-admin/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_management_proto_rawDescOnce sync.Once
	file_admin_v1_management_proto_rawDescData []byte
)

func file_admin_v1_management_proto_rawDescGZIP() []byte {
	file_admin_v1_management_proto_rawDescOnce.Do(func() {
		file_admin_v1_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_management_proto_rawDesc), len(file_admin_v1_management_proto_rawDesc)))
	})
	return file_admin_v1_management_proto_rawDescData
}

var file_admin_v1_management_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_admin_v1_management_proto_goTypes = []any{
	(*ListResourcesRequest)(nil),            // 0: admin.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),           // 1: admin.v1.ListResourcesResponse
	(*CreateResourceRequest)(nil),           // 2: admin.v1.CreateResourceRequest
	(*UpdateResourceRequest)(nil),           // 3: admin.v1.UpdateResourceRequest
	(*DeleteResourceRequest)(nil),           // 4: admin.v1.DeleteResourceRequest
	(*CreateResourceResponse)(nil),          // 5: admin.v1.CreateResourceResponse
	(*UpdateResourceResponse)(nil),          // 6: admin.v1.UpdateResourceResponse
	(*DeleteResourceResponse)(nil),          // 7: admin.v1.DeleteResourceResponse
	(*GetEffectiveSettingsRequest)(nil),     // 8: admin.v1.GetEffectiveSettingsRequest
	(*GetEffectiveSettingsResponse)(nil),    // 9: admin.v1.GetEffectiveSettingsResponse
	(*TestProviderConnectionRequest)(nil),   // 10: admin.v1.TestProviderConnectionRequest
	(*TestProviderConnectionResponse)(nil),  // 11: admin.v1.TestProviderConnectionResponse
	(*RoleResourceGrant)(nil),               // 12: admin.v1.RoleResourceGrant
	(*UpdateRoleAuthorizationRequest)(nil),  // 13: admin.v1.UpdateRoleAuthorizationRequest
	(*UpdateRoleAuthorizationResponse)(nil), // 14: admin.v1.UpdateRoleAuthorizationResponse
	(*UpdateTenantFeaturesRequest)(nil),     // 15: admin.v1.UpdateTenantFeaturesRequest
	(*UpdateTenantFeaturesResponse)(nil),    // 16: admin.v1.UpdateTenantFeaturesResponse
	nil,                                     // 17: admin.v1.ListResourcesRequest.FiltersEntry
	(*structpb.Struct)(nil),                 // 18: google.protobuf.Struct
}
var file_admin_v1_management_proto_depIdxs = []int32{
	17, // 0: admin.v1.ListResourcesRequest.filters:type_name -> admin.v1.ListResourcesRequest.FiltersEntry
	18, // 1: admin.v1.ListResourcesResponse.items:type_name -> google.protobuf.Struct
	18, // 2: admin.v1.CreateResourceRequest.data:type_name -> google.protobuf.Struct
	18, // 3: admin.v1.UpdateResourceRequest.data:type_name -> google.protobuf.Struct
	18, // 4: admin.v1.GetEffectiveSettingsResponse.items:type_name -> google.protobuf.Struct
	12, // 5: admin.v1.UpdateRoleAuthorizationRequest.grants:type_name -> admin.v1.RoleResourceGrant
	0,  // 6: admin.v1.ManagementService.ListResources:input_type -> admin.v1.ListResourcesRequest
	2,  // 7: admin.v1.ManagementService.CreateResource:input_type -> admin.v1.CreateResourceRequest
	3,  // 8: admin.v1.ManagementService.UpdateResource:input_type -> admin.v1.UpdateResourceRequest
	4,  // 9: admin.v1.ManagementService.DeleteResource:input_type -> admin.v1.DeleteResourceRequest
	8,  // 10: admin.v1.ManagementService.GetEffectiveSettings:input_type -> admin.v1.GetEffectiveSettingsRequest
	10, // 11: admin.v1.ManagementService.TestProviderConnection:input_type -> admin.v1.TestProviderConnectionRequest
	13, // 12: admin.v1.ManagementService.UpdateRoleAuthorization:input_type -> admin.v1.UpdateRoleAuthorizationRequest
	15, // 13: admin.v1.ManagementService.UpdateTenantFeatures:input_type -> admin.v1.UpdateTenantFeaturesRequest
	1,  // 14: admin.v1.ManagementService.ListResources:output_type -> admin.v1.ListResourcesResponse
	5,  // 15: admin.v1.ManagementService.CreateResource:output_type -> admin.v1.CreateResourceResponse
	6,  // 16: admin.v1.ManagementService.UpdateResource:output_type -> admin.v1.UpdateResourceResponse
	7,  // 17: admin.v1.ManagementService.DeleteResource:output_type -> admin.v1.DeleteResourceResponse
	9,  // 18: admin.v1.ManagementService.GetEffectiveSettings:output_type -> admin.v1.GetEffectiveSettingsResponse
	11, // 19: admin.v1.ManagementService.TestProviderConnection:output_type -> admin.v1.TestProviderConnectionResponse
	14, // 20: admin.v1.ManagementService.UpdateRoleAuthorization:output_type -> admin.v1.UpdateRoleAuthorizationResponse
	16, // 21: admin.v1.ManagementService.UpdateTenantFeatures:output_type -> admin.v1.UpdateTenantFeaturesResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_admin_v1_management_proto_init() }
func file_admin_v1_management_proto_init() {
	if File_admin_v1_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_management_proto_rawDesc), len(file_admin_v1_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_management_proto_goTypes,
		DependencyIndexes: file_admin_v1_management_proto_depIdxs,
		MessageInfos:      file_admin_v1_management_proto_msgTypes,
	}.Build()
	File_admin_v1_management_proto = out.File
	file_admin_v1_management_proto_goTypes = nil
	file_admin_v1_management_proto_depIdxs = nil
}
