// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/app/admin/internal/data/model"
)

func newAPIAccessLog(db *gorm.DB, opts ...gen.DOOption) aPIAccessLog {
	_aPIAccessLog := aPIAccessLog{}

	_aPIAccessLog.aPIAccessLogDo.UseDB(db, opts...)
	_aPIAccessLog.aPIAccessLogDo.UseModel(&model.APIAccessLog{})

	tableName := _aPIAccessLog.aPIAccessLogDo.TableName()
	_aPIAccessLog.ALL = field.NewAsterisk(tableName)
	_aPIAccessLog.ID = field.NewUint64(tableName, "id")
	_aPIAccessLog.TenantID = field.NewUint64(tableName, "tenant_id")
	_aPIAccessLog.UserID = field.NewUint64(tableName, "user_id")
	_aPIAccessLog.RequestID = field.NewString(tableName, "request_id")
	_aPIAccessLog.Method = field.NewString(tableName, "method")
	_aPIAccessLog.Route = field.NewString(tableName, "route")
	_aPIAccessLog.StatusCode = field.NewUint16(tableName, "status_code")
	_aPIAccessLog.DurationMS = field.NewUint32(tableName, "duration_ms")
	_aPIAccessLog.IP = field.NewString(tableName, "ip")
	_aPIAccessLog.UserAgent = field.NewString(tableName, "user_agent")
	_aPIAccessLog.RequestData = field.NewField(tableName, "request_data")
	_aPIAccessLog.ErrorReason = field.NewString(tableName, "error_reason")
	_aPIAccessLog.CreatedAt = field.NewTime(tableName, "created_at")

	_aPIAccessLog.fillFieldMap()

	return _aPIAccessLog
}

type aPIAccessLog struct {
	aPIAccessLogDo aPIAccessLogDo

	ALL         field.Asterisk
	ID          field.Uint64
	TenantID    field.Uint64
	UserID      field.Uint64
	RequestID   field.String
	Method      field.String
	Route       field.String
	StatusCode  field.Uint16
	DurationMS  field.Uint32
	IP          field.String
	UserAgent   field.String
	RequestData field.Field
	ErrorReason field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (a aPIAccessLog) Table(newTableName string) *aPIAccessLog {
	a.aPIAccessLogDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a aPIAccessLog) As(alias string) *aPIAccessLog {
	a.aPIAccessLogDo.DO = *(a.aPIAccessLogDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *aPIAccessLog) updateTableName(table string) *aPIAccessLog {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.TenantID = field.NewUint64(table, "tenant_id")
	a.UserID = field.NewUint64(table, "user_id")
	a.RequestID = field.NewString(table, "request_id")
	a.Method = field.NewString(table, "method")
	a.Route = field.NewString(table, "route")
	a.StatusCode = field.NewUint16(table, "status_code")
	a.DurationMS = field.NewUint32(table, "duration_ms")
	a.IP = field.NewString(table, "ip")
	a.UserAgent = field.NewString(table, "user_agent")
	a.RequestData = field.NewField(table, "request_data")
	a.ErrorReason = field.NewString(table, "error_reason")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *aPIAccessLog) WithContext(ctx context.Context) IAPIAccessLogDo {
	return a.aPIAccessLogDo.WithContext(ctx)
}

func (a aPIAccessLog) TableName() string { return a.aPIAccessLogDo.TableName() }

func (a aPIAccessLog) Alias() string { return a.aPIAccessLogDo.Alias() }

func (a aPIAccessLog) Columns(cols ...field.Expr) gen.Columns {
	return a.aPIAccessLogDo.Columns(cols...)
}

func (a *aPIAccessLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *aPIAccessLog) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["tenant_id"] = a.TenantID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["request_id"] = a.RequestID
	a.fieldMap["method"] = a.Method
	a.fieldMap["route"] = a.Route
	a.fieldMap["status_code"] = a.StatusCode
	a.fieldMap["duration_ms"] = a.DurationMS
	a.fieldMap["ip"] = a.IP
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["request_data"] = a.RequestData
	a.fieldMap["error_reason"] = a.ErrorReason
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a aPIAccessLog) clone(db *gorm.DB) aPIAccessLog {
	a.aPIAccessLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a aPIAccessLog) replaceDB(db *gorm.DB) aPIAccessLog {
	a.aPIAccessLogDo.ReplaceDB(db)
	return a
}

type aPIAccessLogDo struct{ gen.DO }

type IAPIAccessLogDo interface {
	gen.SubQuery
	Debug() IAPIAccessLogDo
	WithContext(ctx context.Context) IAPIAccessLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAPIAccessLogDo
	WriteDB() IAPIAccessLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAPIAccessLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAPIAccessLogDo
	Not(conds ...gen.Condition) IAPIAccessLogDo
	Or(conds ...gen.Condition) IAPIAccessLogDo
	Select(conds ...field.Expr) IAPIAccessLogDo
	Where(conds ...gen.Condition) IAPIAccessLogDo
	Order(conds ...field.Expr) IAPIAccessLogDo
	Distinct(cols ...field.Expr) IAPIAccessLogDo
	Omit(cols ...field.Expr) IAPIAccessLogDo
	Join(table schema.Tabler, on ...field.Expr) IAPIAccessLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAPIAccessLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAPIAccessLogDo
	Group(cols ...field.Expr) IAPIAccessLogDo
	Having(conds ...gen.Condition) IAPIAccessLogDo
	Limit(limit int) IAPIAccessLogDo
	Offset(offset int) IAPIAccessLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAPIAccessLogDo
	Unscoped() IAPIAccessLogDo
	Create(values ...*model.APIAccessLog) error
	CreateInBatches(values []*model.APIAccessLog, batchSize int) error
	Save(values ...*model.APIAccessLog) error
	First() (*model.APIAccessLog, error)
	Take() (*model.APIAccessLog, error)
	Last() (*model.APIAccessLog, error)
	Find() ([]*model.APIAccessLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.APIAccessLog, err error)
	FindInBatches(result *[]*model.APIAccessLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.APIAccessLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAPIAccessLogDo
	Assign(attrs ...field.AssignExpr) IAPIAccessLogDo
	Joins(fields ...field.RelationField) IAPIAccessLogDo
	Preload(fields ...field.RelationField) IAPIAccessLogDo
	FirstOrInit() (*model.APIAccessLog, error)
	FirstOrCreate() (*model.APIAccessLog, error)
	FindByPage(offset int, limit int) (result []*model.APIAccessLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAPIAccessLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a aPIAccessLogDo) Debug() IAPIAccessLogDo {
	return a.withDO(a.DO.Debug())
}

func (a aPIAccessLogDo) WithContext(ctx context.Context) IAPIAccessLogDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a aPIAccessLogDo) ReadDB() IAPIAccessLogDo {
	return a.Clauses(dbresolver.Read)
}

func (a aPIAccessLogDo) WriteDB() IAPIAccessLogDo {
	return a.Clauses(dbresolver.Write)
}

func (a aPIAccessLogDo) Session(config *gorm.Session) IAPIAccessLogDo {
	return a.withDO(a.DO.Session(config))
}

func (a aPIAccessLogDo) Clauses(conds ...clause.Expression) IAPIAccessLogDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a aPIAccessLogDo) Returning(value interface{}, columns ...string) IAPIAccessLogDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a aPIAccessLogDo) Not(conds ...gen.Condition) IAPIAccessLogDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a aPIAccessLogDo) Or(conds ...gen.Condition) IAPIAccessLogDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a aPIAccessLogDo) Select(conds ...field.Expr) IAPIAccessLogDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a aPIAccessLogDo) Where(conds ...gen.Condition) IAPIAccessLogDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a aPIAccessLogDo) Order(conds ...field.Expr) IAPIAccessLogDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a aPIAccessLogDo) Distinct(cols ...field.Expr) IAPIAccessLogDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a aPIAccessLogDo) Omit(cols ...field.Expr) IAPIAccessLogDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a aPIAccessLogDo) Join(table schema.Tabler, on ...field.Expr) IAPIAccessLogDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a aPIAccessLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAPIAccessLogDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a aPIAccessLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IAPIAccessLogDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a aPIAccessLogDo) Group(cols ...field.Expr) IAPIAccessLogDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a aPIAccessLogDo) Having(conds ...gen.Condition) IAPIAccessLogDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a aPIAccessLogDo) Limit(limit int) IAPIAccessLogDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a aPIAccessLogDo) Offset(offset int) IAPIAccessLogDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a aPIAccessLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAPIAccessLogDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a aPIAccessLogDo) Unscoped() IAPIAccessLogDo {
	return a.withDO(a.DO.Unscoped())
}

func (a aPIAccessLogDo) Create(values ...*model.APIAccessLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a aPIAccessLogDo) CreateInBatches(values []*model.APIAccessLog, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a aPIAccessLogDo) Save(values ...*model.APIAccessLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a aPIAccessLogDo) First() (*model.APIAccessLog, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccessLog), nil
	}
}

func (a aPIAccessLogDo) Take() (*model.APIAccessLog, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccessLog), nil
	}
}

func (a aPIAccessLogDo) Last() (*model.APIAccessLog, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccessLog), nil
	}
}

func (a aPIAccessLogDo) Find() ([]*model.APIAccessLog, error) {
	result, err := a.DO.Find()
	return result.([]*model.APIAccessLog), err
}

func (a aPIAccessLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.APIAccessLog, err error) {
	buf := make([]*model.APIAccessLog, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a aPIAccessLogDo) FindInBatches(result *[]*model.APIAccessLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a aPIAccessLogDo) Attrs(attrs ...field.AssignExpr) IAPIAccessLogDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a aPIAccessLogDo) Assign(attrs ...field.AssignExpr) IAPIAccessLogDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a aPIAccessLogDo) Joins(fields ...field.RelationField) IAPIAccessLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a aPIAccessLogDo) Preload(fields ...field.RelationField) IAPIAccessLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a aPIAccessLogDo) FirstOrInit() (*model.APIAccessLog, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccessLog), nil
	}
}

func (a aPIAccessLogDo) FirstOrCreate() (*model.APIAccessLog, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.APIAccessLog), nil
	}
}

func (a aPIAccessLogDo) FindByPage(offset int, limit int) (result []*model.APIAccessLog, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a aPIAccessLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a aPIAccessLogDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a aPIAccessLogDo) Delete(models ...*model.APIAccessLog) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *aPIAccessLogDo) withDO(do gen.Dao) *aPIAccessLogDo {
	a.DO = *do.(*gen.DO)
	return a
}
