// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/app/admin/internal/data/model"
)

func newDictionaryItem(db *gorm.DB, opts ...gen.DOOption) dictionaryItem {
	_dictionaryItem := dictionaryItem{}

	_dictionaryItem.dictionaryItemDo.UseDB(db, opts...)
	_dictionaryItem.dictionaryItemDo.UseModel(&model.DictionaryItem{})

	tableName := _dictionaryItem.dictionaryItemDo.TableName()
	_dictionaryItem.ALL = field.NewAsterisk(tableName)
	_dictionaryItem.ID = field.NewUint64(tableName, "id")
	_dictionaryItem.TenantID = field.NewUint64(tableName, "tenant_id")
	_dictionaryItem.TypeID = field.NewUint64(tableName, "type_id")
	_dictionaryItem.ItemValue = field.NewString(tableName, "item_value")
	_dictionaryItem.Label = field.NewString(tableName, "label")
	_dictionaryItem.SortOrder = field.NewInt32(tableName, "sort_order")
	_dictionaryItem.Status = field.NewUint8(tableName, "status")
	_dictionaryItem.CreatedAt = field.NewTime(tableName, "created_at")
	_dictionaryItem.UpdatedAt = field.NewTime(tableName, "updated_at")
	_dictionaryItem.DeletedAt = field.NewField(tableName, "deleted_at")

	_dictionaryItem.fillFieldMap()

	return _dictionaryItem
}

// dictionaryItem 参数字典项表
type dictionaryItem struct {
	dictionaryItemDo dictionaryItemDo

	ALL       field.Asterisk
	ID        field.Uint64 // 字典项主键
	TenantID  field.Uint64 // 所属租户ID，0表示平台字典
	TypeID    field.Uint64 // 字典类型ID
	ItemValue field.String // 字典项值
	Label     field.String // 字典项显示名称
	SortOrder field.Int32  // 显示排序值
	Status    field.Uint8  // 字典项状态：1启用，2禁用
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 逻辑删除时间

	fieldMap map[string]field.Expr
}

func (d dictionaryItem) Table(newTableName string) *dictionaryItem {
	d.dictionaryItemDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dictionaryItem) As(alias string) *dictionaryItem {
	d.dictionaryItemDo.DO = *(d.dictionaryItemDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dictionaryItem) updateTableName(table string) *dictionaryItem {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint64(table, "id")
	d.TenantID = field.NewUint64(table, "tenant_id")
	d.TypeID = field.NewUint64(table, "type_id")
	d.ItemValue = field.NewString(table, "item_value")
	d.Label = field.NewString(table, "label")
	d.SortOrder = field.NewInt32(table, "sort_order")
	d.Status = field.NewUint8(table, "status")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DeletedAt = field.NewField(table, "deleted_at")

	d.fillFieldMap()

	return d
}

func (d *dictionaryItem) WithContext(ctx context.Context) IDictionaryItemDo {
	return d.dictionaryItemDo.WithContext(ctx)
}

func (d dictionaryItem) TableName() string { return d.dictionaryItemDo.TableName() }

func (d dictionaryItem) Alias() string { return d.dictionaryItemDo.Alias() }

func (d dictionaryItem) Columns(cols ...field.Expr) gen.Columns {
	return d.dictionaryItemDo.Columns(cols...)
}

func (d *dictionaryItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dictionaryItem) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["tenant_id"] = d.TenantID
	d.fieldMap["type_id"] = d.TypeID
	d.fieldMap["item_value"] = d.ItemValue
	d.fieldMap["label"] = d.Label
	d.fieldMap["sort_order"] = d.SortOrder
	d.fieldMap["status"] = d.Status
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["deleted_at"] = d.DeletedAt
}

func (d dictionaryItem) clone(db *gorm.DB) dictionaryItem {
	d.dictionaryItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dictionaryItem) replaceDB(db *gorm.DB) dictionaryItem {
	d.dictionaryItemDo.ReplaceDB(db)
	return d
}

type dictionaryItemDo struct{ gen.DO }

type IDictionaryItemDo interface {
	gen.SubQuery
	Debug() IDictionaryItemDo
	WithContext(ctx context.Context) IDictionaryItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDictionaryItemDo
	WriteDB() IDictionaryItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDictionaryItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDictionaryItemDo
	Not(conds ...gen.Condition) IDictionaryItemDo
	Or(conds ...gen.Condition) IDictionaryItemDo
	Select(conds ...field.Expr) IDictionaryItemDo
	Where(conds ...gen.Condition) IDictionaryItemDo
	Order(conds ...field.Expr) IDictionaryItemDo
	Distinct(cols ...field.Expr) IDictionaryItemDo
	Omit(cols ...field.Expr) IDictionaryItemDo
	Join(table schema.Tabler, on ...field.Expr) IDictionaryItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDictionaryItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDictionaryItemDo
	Group(cols ...field.Expr) IDictionaryItemDo
	Having(conds ...gen.Condition) IDictionaryItemDo
	Limit(limit int) IDictionaryItemDo
	Offset(offset int) IDictionaryItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionaryItemDo
	Unscoped() IDictionaryItemDo
	Create(values ...*model.DictionaryItem) error
	CreateInBatches(values []*model.DictionaryItem, batchSize int) error
	Save(values ...*model.DictionaryItem) error
	First() (*model.DictionaryItem, error)
	Take() (*model.DictionaryItem, error)
	Last() (*model.DictionaryItem, error)
	Find() ([]*model.DictionaryItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DictionaryItem, err error)
	FindInBatches(result *[]*model.DictionaryItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DictionaryItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDictionaryItemDo
	Assign(attrs ...field.AssignExpr) IDictionaryItemDo
	Joins(fields ...field.RelationField) IDictionaryItemDo
	Preload(fields ...field.RelationField) IDictionaryItemDo
	FirstOrInit() (*model.DictionaryItem, error)
	FirstOrCreate() (*model.DictionaryItem, error)
	FindByPage(offset int, limit int) (result []*model.DictionaryItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDictionaryItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dictionaryItemDo) Debug() IDictionaryItemDo {
	return d.withDO(d.DO.Debug())
}

func (d dictionaryItemDo) WithContext(ctx context.Context) IDictionaryItemDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dictionaryItemDo) ReadDB() IDictionaryItemDo {
	return d.Clauses(dbresolver.Read)
}

func (d dictionaryItemDo) WriteDB() IDictionaryItemDo {
	return d.Clauses(dbresolver.Write)
}

func (d dictionaryItemDo) Session(config *gorm.Session) IDictionaryItemDo {
	return d.withDO(d.DO.Session(config))
}

func (d dictionaryItemDo) Clauses(conds ...clause.Expression) IDictionaryItemDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dictionaryItemDo) Returning(value interface{}, columns ...string) IDictionaryItemDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dictionaryItemDo) Not(conds ...gen.Condition) IDictionaryItemDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dictionaryItemDo) Or(conds ...gen.Condition) IDictionaryItemDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dictionaryItemDo) Select(conds ...field.Expr) IDictionaryItemDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dictionaryItemDo) Where(conds ...gen.Condition) IDictionaryItemDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dictionaryItemDo) Order(conds ...field.Expr) IDictionaryItemDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dictionaryItemDo) Distinct(cols ...field.Expr) IDictionaryItemDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dictionaryItemDo) Omit(cols ...field.Expr) IDictionaryItemDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dictionaryItemDo) Join(table schema.Tabler, on ...field.Expr) IDictionaryItemDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dictionaryItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDictionaryItemDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dictionaryItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IDictionaryItemDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dictionaryItemDo) Group(cols ...field.Expr) IDictionaryItemDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dictionaryItemDo) Having(conds ...gen.Condition) IDictionaryItemDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dictionaryItemDo) Limit(limit int) IDictionaryItemDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dictionaryItemDo) Offset(offset int) IDictionaryItemDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dictionaryItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDictionaryItemDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dictionaryItemDo) Unscoped() IDictionaryItemDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dictionaryItemDo) Create(values ...*model.DictionaryItem) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dictionaryItemDo) CreateInBatches(values []*model.DictionaryItem, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dictionaryItemDo) Save(values ...*model.DictionaryItem) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dictionaryItemDo) First() (*model.DictionaryItem, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryItem), nil
	}
}

func (d dictionaryItemDo) Take() (*model.DictionaryItem, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryItem), nil
	}
}

func (d dictionaryItemDo) Last() (*model.DictionaryItem, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryItem), nil
	}
}

func (d dictionaryItemDo) Find() ([]*model.DictionaryItem, error) {
	result, err := d.DO.Find()
	return result.([]*model.DictionaryItem), err
}

func (d dictionaryItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DictionaryItem, err error) {
	buf := make([]*model.DictionaryItem, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dictionaryItemDo) FindInBatches(result *[]*model.DictionaryItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dictionaryItemDo) Attrs(attrs ...field.AssignExpr) IDictionaryItemDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dictionaryItemDo) Assign(attrs ...field.AssignExpr) IDictionaryItemDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dictionaryItemDo) Joins(fields ...field.RelationField) IDictionaryItemDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dictionaryItemDo) Preload(fields ...field.RelationField) IDictionaryItemDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dictionaryItemDo) FirstOrInit() (*model.DictionaryItem, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryItem), nil
	}
}

func (d dictionaryItemDo) FirstOrCreate() (*model.DictionaryItem, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictionaryItem), nil
	}
}

func (d dictionaryItemDo) FindByPage(offset int, limit int) (result []*model.DictionaryItem, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dictionaryItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dictionaryItemDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dictionaryItemDo) Delete(models ...*model.DictionaryItem) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dictionaryItemDo) withDO(do gen.Dao) *dictionaryItemDo {
	d.DO = *do.(*gen.DO)
	return d
}
