// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/app/admin/internal/data/model"
)

func newLogExport(db *gorm.DB, opts ...gen.DOOption) logExport {
	_logExport := logExport{}

	_logExport.logExportDo.UseDB(db, opts...)
	_logExport.logExportDo.UseModel(&model.LogExport{})

	tableName := _logExport.logExportDo.TableName()
	_logExport.ALL = field.NewAsterisk(tableName)
	_logExport.ID = field.NewString(tableName, "id")
	_logExport.TenantID = field.NewUint64(tableName, "tenant_id")
	_logExport.UserID = field.NewUint64(tableName, "user_id")
	_logExport.MemberID = field.NewUint64(tableName, "member_id")
	_logExport.LogType = field.NewString(tableName, "log_type")
	_logExport.Keyword = field.NewString(tableName, "keyword")
	_logExport.Filters = field.NewField(tableName, "filters")
	_logExport.PayloadVersion = field.NewUint16(tableName, "payload_version")
	_logExport.IdempotencyKey = field.NewString(tableName, "idempotency_key")
	_logExport.Status = field.NewUint8(tableName, "status")
	_logExport.RowCount = field.NewUint32(tableName, "row_count")
	_logExport.FileID = field.NewString(tableName, "file_id")
	_logExport.RetryCount = field.NewUint32(tableName, "retry_count")
	_logExport.NextRetryAt = field.NewTime(tableName, "next_retry_at")
	_logExport.DispatchedAt = field.NewTime(tableName, "dispatched_at")
	_logExport.FailureReason = field.NewString(tableName, "failure_reason")
	_logExport.CreatedAt = field.NewTime(tableName, "created_at")
	_logExport.StartedAt = field.NewTime(tableName, "started_at")
	_logExport.FinishedAt = field.NewTime(tableName, "finished_at")
	_logExport.UpdatedAt = field.NewTime(tableName, "updated_at")

	_logExport.fillFieldMap()

	return _logExport
}

type logExport struct {
	logExportDo logExportDo

	ALL            field.Asterisk
	ID             field.String
	TenantID       field.Uint64
	UserID         field.Uint64
	MemberID       field.Uint64
	LogType        field.String
	Keyword        field.String
	Filters        field.Field
	PayloadVersion field.Uint16
	IdempotencyKey field.String
	Status         field.Uint8
	RowCount       field.Uint32
	FileID         field.String
	RetryCount     field.Uint32
	NextRetryAt    field.Time
	DispatchedAt   field.Time
	FailureReason  field.String
	CreatedAt      field.Time
	StartedAt      field.Time
	FinishedAt     field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (l logExport) Table(newTableName string) *logExport {
	l.logExportDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l logExport) As(alias string) *logExport {
	l.logExportDo.DO = *(l.logExportDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *logExport) updateTableName(table string) *logExport {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewString(table, "id")
	l.TenantID = field.NewUint64(table, "tenant_id")
	l.UserID = field.NewUint64(table, "user_id")
	l.MemberID = field.NewUint64(table, "member_id")
	l.LogType = field.NewString(table, "log_type")
	l.Keyword = field.NewString(table, "keyword")
	l.Filters = field.NewField(table, "filters")
	l.PayloadVersion = field.NewUint16(table, "payload_version")
	l.IdempotencyKey = field.NewString(table, "idempotency_key")
	l.Status = field.NewUint8(table, "status")
	l.RowCount = field.NewUint32(table, "row_count")
	l.FileID = field.NewString(table, "file_id")
	l.RetryCount = field.NewUint32(table, "retry_count")
	l.NextRetryAt = field.NewTime(table, "next_retry_at")
	l.DispatchedAt = field.NewTime(table, "dispatched_at")
	l.FailureReason = field.NewString(table, "failure_reason")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.StartedAt = field.NewTime(table, "started_at")
	l.FinishedAt = field.NewTime(table, "finished_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *logExport) WithContext(ctx context.Context) ILogExportDo {
	return l.logExportDo.WithContext(ctx)
}

func (l logExport) TableName() string { return l.logExportDo.TableName() }

func (l logExport) Alias() string { return l.logExportDo.Alias() }

func (l logExport) Columns(cols ...field.Expr) gen.Columns { return l.logExportDo.Columns(cols...) }

func (l *logExport) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *logExport) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 20)
	l.fieldMap["id"] = l.ID
	l.fieldMap["tenant_id"] = l.TenantID
	l.fieldMap["user_id"] = l.UserID
	l.fieldMap["member_id"] = l.MemberID
	l.fieldMap["log_type"] = l.LogType
	l.fieldMap["keyword"] = l.Keyword
	l.fieldMap["filters"] = l.Filters
	l.fieldMap["payload_version"] = l.PayloadVersion
	l.fieldMap["idempotency_key"] = l.IdempotencyKey
	l.fieldMap["status"] = l.Status
	l.fieldMap["row_count"] = l.RowCount
	l.fieldMap["file_id"] = l.FileID
	l.fieldMap["retry_count"] = l.RetryCount
	l.fieldMap["next_retry_at"] = l.NextRetryAt
	l.fieldMap["dispatched_at"] = l.DispatchedAt
	l.fieldMap["failure_reason"] = l.FailureReason
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["started_at"] = l.StartedAt
	l.fieldMap["finished_at"] = l.FinishedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l logExport) clone(db *gorm.DB) logExport {
	l.logExportDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l logExport) replaceDB(db *gorm.DB) logExport {
	l.logExportDo.ReplaceDB(db)
	return l
}

type logExportDo struct{ gen.DO }

type ILogExportDo interface {
	gen.SubQuery
	Debug() ILogExportDo
	WithContext(ctx context.Context) ILogExportDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILogExportDo
	WriteDB() ILogExportDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILogExportDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILogExportDo
	Not(conds ...gen.Condition) ILogExportDo
	Or(conds ...gen.Condition) ILogExportDo
	Select(conds ...field.Expr) ILogExportDo
	Where(conds ...gen.Condition) ILogExportDo
	Order(conds ...field.Expr) ILogExportDo
	Distinct(cols ...field.Expr) ILogExportDo
	Omit(cols ...field.Expr) ILogExportDo
	Join(table schema.Tabler, on ...field.Expr) ILogExportDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILogExportDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILogExportDo
	Group(cols ...field.Expr) ILogExportDo
	Having(conds ...gen.Condition) ILogExportDo
	Limit(limit int) ILogExportDo
	Offset(offset int) ILogExportDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILogExportDo
	Unscoped() ILogExportDo
	Create(values ...*model.LogExport) error
	CreateInBatches(values []*model.LogExport, batchSize int) error
	Save(values ...*model.LogExport) error
	First() (*model.LogExport, error)
	Take() (*model.LogExport, error)
	Last() (*model.LogExport, error)
	Find() ([]*model.LogExport, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LogExport, err error)
	FindInBatches(result *[]*model.LogExport, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LogExport) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILogExportDo
	Assign(attrs ...field.AssignExpr) ILogExportDo
	Joins(fields ...field.RelationField) ILogExportDo
	Preload(fields ...field.RelationField) ILogExportDo
	FirstOrInit() (*model.LogExport, error)
	FirstOrCreate() (*model.LogExport, error)
	FindByPage(offset int, limit int) (result []*model.LogExport, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILogExportDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l logExportDo) Debug() ILogExportDo {
	return l.withDO(l.DO.Debug())
}

func (l logExportDo) WithContext(ctx context.Context) ILogExportDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l logExportDo) ReadDB() ILogExportDo {
	return l.Clauses(dbresolver.Read)
}

func (l logExportDo) WriteDB() ILogExportDo {
	return l.Clauses(dbresolver.Write)
}

func (l logExportDo) Session(config *gorm.Session) ILogExportDo {
	return l.withDO(l.DO.Session(config))
}

func (l logExportDo) Clauses(conds ...clause.Expression) ILogExportDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l logExportDo) Returning(value interface{}, columns ...string) ILogExportDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l logExportDo) Not(conds ...gen.Condition) ILogExportDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l logExportDo) Or(conds ...gen.Condition) ILogExportDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l logExportDo) Select(conds ...field.Expr) ILogExportDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l logExportDo) Where(conds ...gen.Condition) ILogExportDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l logExportDo) Order(conds ...field.Expr) ILogExportDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l logExportDo) Distinct(cols ...field.Expr) ILogExportDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l logExportDo) Omit(cols ...field.Expr) ILogExportDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l logExportDo) Join(table schema.Tabler, on ...field.Expr) ILogExportDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l logExportDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILogExportDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l logExportDo) RightJoin(table schema.Tabler, on ...field.Expr) ILogExportDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l logExportDo) Group(cols ...field.Expr) ILogExportDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l logExportDo) Having(conds ...gen.Condition) ILogExportDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l logExportDo) Limit(limit int) ILogExportDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l logExportDo) Offset(offset int) ILogExportDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l logExportDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILogExportDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l logExportDo) Unscoped() ILogExportDo {
	return l.withDO(l.DO.Unscoped())
}

func (l logExportDo) Create(values ...*model.LogExport) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l logExportDo) CreateInBatches(values []*model.LogExport, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l logExportDo) Save(values ...*model.LogExport) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l logExportDo) First() (*model.LogExport, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogExport), nil
	}
}

func (l logExportDo) Take() (*model.LogExport, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogExport), nil
	}
}

func (l logExportDo) Last() (*model.LogExport, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogExport), nil
	}
}

func (l logExportDo) Find() ([]*model.LogExport, error) {
	result, err := l.DO.Find()
	return result.([]*model.LogExport), err
}

func (l logExportDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LogExport, err error) {
	buf := make([]*model.LogExport, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l logExportDo) FindInBatches(result *[]*model.LogExport, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l logExportDo) Attrs(attrs ...field.AssignExpr) ILogExportDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l logExportDo) Assign(attrs ...field.AssignExpr) ILogExportDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l logExportDo) Joins(fields ...field.RelationField) ILogExportDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l logExportDo) Preload(fields ...field.RelationField) ILogExportDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l logExportDo) FirstOrInit() (*model.LogExport, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogExport), nil
	}
}

func (l logExportDo) FirstOrCreate() (*model.LogExport, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LogExport), nil
	}
}

func (l logExportDo) FindByPage(offset int, limit int) (result []*model.LogExport, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l logExportDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l logExportDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l logExportDo) Delete(models ...*model.LogExport) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *logExportDo) withDO(do gen.Dao) *logExportDo {
	l.DO = *do.(*gen.DO)
	return l
}
