// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/app/admin/internal/data/model"
)

func newPosition(db *gorm.DB, opts ...gen.DOOption) position {
	_position := position{}

	_position.positionDo.UseDB(db, opts...)
	_position.positionDo.UseModel(&model.Position{})

	tableName := _position.positionDo.TableName()
	_position.ALL = field.NewAsterisk(tableName)
	_position.ID = field.NewUint64(tableName, "id")
	_position.TenantID = field.NewUint64(tableName, "tenant_id")
	_position.Code = field.NewString(tableName, "code")
	_position.Name = field.NewString(tableName, "name")
	_position.SortOrder = field.NewInt32(tableName, "sort_order")
	_position.Status = field.NewUint8(tableName, "status")
	_position.CreatedAt = field.NewTime(tableName, "created_at")
	_position.UpdatedAt = field.NewTime(tableName, "updated_at")
	_position.DeletedAt = field.NewField(tableName, "deleted_at")

	_position.fillFieldMap()

	return _position
}

// position 岗位表
type position struct {
	positionDo positionDo

	ALL       field.Asterisk
	ID        field.Uint64 // 岗位主键
	TenantID  field.Uint64 // 所属租户ID
	Code      field.String // 租户内唯一岗位编码
	Name      field.String // 岗位名称
	SortOrder field.Int32  // 显示排序值
	Status    field.Uint8  // 岗位状态：1启用，2禁用
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 逻辑删除时间

	fieldMap map[string]field.Expr
}

func (p position) Table(newTableName string) *position {
	p.positionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p position) As(alias string) *position {
	p.positionDo.DO = *(p.positionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *position) updateTableName(table string) *position {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint64(table, "id")
	p.TenantID = field.NewUint64(table, "tenant_id")
	p.Code = field.NewString(table, "code")
	p.Name = field.NewString(table, "name")
	p.SortOrder = field.NewInt32(table, "sort_order")
	p.Status = field.NewUint8(table, "status")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *position) WithContext(ctx context.Context) IPositionDo { return p.positionDo.WithContext(ctx) }

func (p position) TableName() string { return p.positionDo.TableName() }

func (p position) Alias() string { return p.positionDo.Alias() }

func (p position) Columns(cols ...field.Expr) gen.Columns { return p.positionDo.Columns(cols...) }

func (p *position) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *position) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["tenant_id"] = p.TenantID
	p.fieldMap["code"] = p.Code
	p.fieldMap["name"] = p.Name
	p.fieldMap["sort_order"] = p.SortOrder
	p.fieldMap["status"] = p.Status
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
}

func (p position) clone(db *gorm.DB) position {
	p.positionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p position) replaceDB(db *gorm.DB) position {
	p.positionDo.ReplaceDB(db)
	return p
}

type positionDo struct{ gen.DO }

type IPositionDo interface {
	gen.SubQuery
	Debug() IPositionDo
	WithContext(ctx context.Context) IPositionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPositionDo
	WriteDB() IPositionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPositionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPositionDo
	Not(conds ...gen.Condition) IPositionDo
	Or(conds ...gen.Condition) IPositionDo
	Select(conds ...field.Expr) IPositionDo
	Where(conds ...gen.Condition) IPositionDo
	Order(conds ...field.Expr) IPositionDo
	Distinct(cols ...field.Expr) IPositionDo
	Omit(cols ...field.Expr) IPositionDo
	Join(table schema.Tabler, on ...field.Expr) IPositionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPositionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPositionDo
	Group(cols ...field.Expr) IPositionDo
	Having(conds ...gen.Condition) IPositionDo
	Limit(limit int) IPositionDo
	Offset(offset int) IPositionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPositionDo
	Unscoped() IPositionDo
	Create(values ...*model.Position) error
	CreateInBatches(values []*model.Position, batchSize int) error
	Save(values ...*model.Position) error
	First() (*model.Position, error)
	Take() (*model.Position, error)
	Last() (*model.Position, error)
	Find() ([]*model.Position, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Position, err error)
	FindInBatches(result *[]*model.Position, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Position) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPositionDo
	Assign(attrs ...field.AssignExpr) IPositionDo
	Joins(fields ...field.RelationField) IPositionDo
	Preload(fields ...field.RelationField) IPositionDo
	FirstOrInit() (*model.Position, error)
	FirstOrCreate() (*model.Position, error)
	FindByPage(offset int, limit int) (result []*model.Position, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPositionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p positionDo) Debug() IPositionDo {
	return p.withDO(p.DO.Debug())
}

func (p positionDo) WithContext(ctx context.Context) IPositionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p positionDo) ReadDB() IPositionDo {
	return p.Clauses(dbresolver.Read)
}

func (p positionDo) WriteDB() IPositionDo {
	return p.Clauses(dbresolver.Write)
}

func (p positionDo) Session(config *gorm.Session) IPositionDo {
	return p.withDO(p.DO.Session(config))
}

func (p positionDo) Clauses(conds ...clause.Expression) IPositionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p positionDo) Returning(value interface{}, columns ...string) IPositionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p positionDo) Not(conds ...gen.Condition) IPositionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p positionDo) Or(conds ...gen.Condition) IPositionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p positionDo) Select(conds ...field.Expr) IPositionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p positionDo) Where(conds ...gen.Condition) IPositionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p positionDo) Order(conds ...field.Expr) IPositionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p positionDo) Distinct(cols ...field.Expr) IPositionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p positionDo) Omit(cols ...field.Expr) IPositionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p positionDo) Join(table schema.Tabler, on ...field.Expr) IPositionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p positionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPositionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p positionDo) RightJoin(table schema.Tabler, on ...field.Expr) IPositionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p positionDo) Group(cols ...field.Expr) IPositionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p positionDo) Having(conds ...gen.Condition) IPositionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p positionDo) Limit(limit int) IPositionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p positionDo) Offset(offset int) IPositionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p positionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPositionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p positionDo) Unscoped() IPositionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p positionDo) Create(values ...*model.Position) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p positionDo) CreateInBatches(values []*model.Position, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p positionDo) Save(values ...*model.Position) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p positionDo) First() (*model.Position, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Position), nil
	}
}

func (p positionDo) Take() (*model.Position, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Position), nil
	}
}

func (p positionDo) Last() (*model.Position, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Position), nil
	}
}

func (p positionDo) Find() ([]*model.Position, error) {
	result, err := p.DO.Find()
	return result.([]*model.Position), err
}

func (p positionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Position, err error) {
	buf := make([]*model.Position, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p positionDo) FindInBatches(result *[]*model.Position, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p positionDo) Attrs(attrs ...field.AssignExpr) IPositionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p positionDo) Assign(attrs ...field.AssignExpr) IPositionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p positionDo) Joins(fields ...field.RelationField) IPositionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p positionDo) Preload(fields ...field.RelationField) IPositionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p positionDo) FirstOrInit() (*model.Position, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Position), nil
	}
}

func (p positionDo) FirstOrCreate() (*model.Position, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Position), nil
	}
}

func (p positionDo) FindByPage(offset int, limit int) (result []*model.Position, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p positionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p positionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p positionDo) Delete(models ...*model.Position) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *positionDo) withDO(do gen.Dao) *positionDo {
	p.DO = *do.(*gen.DO)
	return p
}
