// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/app/admin/internal/data/model"
)

func newTenantMember(db *gorm.DB, opts ...gen.DOOption) tenantMember {
	_tenantMember := tenantMember{}

	_tenantMember.tenantMemberDo.UseDB(db, opts...)
	_tenantMember.tenantMemberDo.UseModel(&model.TenantMember{})

	tableName := _tenantMember.tenantMemberDo.TableName()
	_tenantMember.ALL = field.NewAsterisk(tableName)
	_tenantMember.ID = field.NewUint64(tableName, "id")
	_tenantMember.TenantID = field.NewUint64(tableName, "tenant_id")
	_tenantMember.UserID = field.NewUint64(tableName, "user_id")
	_tenantMember.PrimaryDepartmentID = field.NewUint64(tableName, "primary_department_id")
	_tenantMember.PositionID = field.NewUint64(tableName, "position_id")
	_tenantMember.DisplayName = field.NewString(tableName, "display_name")
	_tenantMember.Status = field.NewUint8(tableName, "status")
	_tenantMember.IsTenantAdmin = field.NewBool(tableName, "is_tenant_admin")
	_tenantMember.JoinedAt = field.NewTime(tableName, "joined_at")
	_tenantMember.CreatedAt = field.NewTime(tableName, "created_at")
	_tenantMember.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tenantMember.DeletedAt = field.NewField(tableName, "deleted_at")
	_tenantMember.User = tenantMemberBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.User"),
	}

	_tenantMember.PrimaryDepartment = tenantMemberBelongsToPrimaryDepartment{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("PrimaryDepartment", "model.Department"),
	}

	_tenantMember.Position = tenantMemberBelongsToPosition{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Position", "model.Position"),
	}

	_tenantMember.fillFieldMap()

	return _tenantMember
}

// tenantMember 租户成员表
type tenantMember struct {
	tenantMemberDo tenantMemberDo

	ALL                 field.Asterisk
	ID                  field.Uint64 // 租户成员主键
	TenantID            field.Uint64 // 所属租户ID
	UserID              field.Uint64 // 关联全局用户ID
	PrimaryDepartmentID field.Uint64 // 主部门ID，0表示未分配
	PositionID          field.Uint64 // 岗位ID，0表示未分配
	DisplayName         field.String // 租户内显示名称
	Status              field.Uint8  // 成员状态：1启用，2禁用
	IsTenantAdmin       field.Bool   // 是否租户管理员：0否，1是
	JoinedAt            field.Time   // 加入租户时间
	CreatedAt           field.Time   // 创建时间
	UpdatedAt           field.Time   // 更新时间
	DeletedAt           field.Field  // 逻辑删除时间
	User                tenantMemberBelongsToUser

	PrimaryDepartment tenantMemberBelongsToPrimaryDepartment

	Position tenantMemberBelongsToPosition

	fieldMap map[string]field.Expr
}

func (t tenantMember) Table(newTableName string) *tenantMember {
	t.tenantMemberDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tenantMember) As(alias string) *tenantMember {
	t.tenantMemberDo.DO = *(t.tenantMemberDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tenantMember) updateTableName(table string) *tenantMember {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint64(table, "id")
	t.TenantID = field.NewUint64(table, "tenant_id")
	t.UserID = field.NewUint64(table, "user_id")
	t.PrimaryDepartmentID = field.NewUint64(table, "primary_department_id")
	t.PositionID = field.NewUint64(table, "position_id")
	t.DisplayName = field.NewString(table, "display_name")
	t.Status = field.NewUint8(table, "status")
	t.IsTenantAdmin = field.NewBool(table, "is_tenant_admin")
	t.JoinedAt = field.NewTime(table, "joined_at")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tenantMember) WithContext(ctx context.Context) ITenantMemberDo {
	return t.tenantMemberDo.WithContext(ctx)
}

func (t tenantMember) TableName() string { return t.tenantMemberDo.TableName() }

func (t tenantMember) Alias() string { return t.tenantMemberDo.Alias() }

func (t tenantMember) Columns(cols ...field.Expr) gen.Columns {
	return t.tenantMemberDo.Columns(cols...)
}

func (t *tenantMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tenantMember) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 15)
	t.fieldMap["id"] = t.ID
	t.fieldMap["tenant_id"] = t.TenantID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["primary_department_id"] = t.PrimaryDepartmentID
	t.fieldMap["position_id"] = t.PositionID
	t.fieldMap["display_name"] = t.DisplayName
	t.fieldMap["status"] = t.Status
	t.fieldMap["is_tenant_admin"] = t.IsTenantAdmin
	t.fieldMap["joined_at"] = t.JoinedAt
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt

}

func (t tenantMember) clone(db *gorm.DB) tenantMember {
	t.tenantMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	t.User.db = db.Session(&gorm.Session{Initialized: true})
	t.User.db.Statement.ConnPool = db.Statement.ConnPool
	t.PrimaryDepartment.db = db.Session(&gorm.Session{Initialized: true})
	t.PrimaryDepartment.db.Statement.ConnPool = db.Statement.ConnPool
	t.Position.db = db.Session(&gorm.Session{Initialized: true})
	t.Position.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t tenantMember) replaceDB(db *gorm.DB) tenantMember {
	t.tenantMemberDo.ReplaceDB(db)
	t.User.db = db.Session(&gorm.Session{})
	t.PrimaryDepartment.db = db.Session(&gorm.Session{})
	t.Position.db = db.Session(&gorm.Session{})
	return t
}

type tenantMemberBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a tenantMemberBelongsToUser) Where(conds ...field.Expr) *tenantMemberBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a tenantMemberBelongsToUser) WithContext(ctx context.Context) *tenantMemberBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a tenantMemberBelongsToUser) Session(session *gorm.Session) *tenantMemberBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a tenantMemberBelongsToUser) Model(m *model.TenantMember) *tenantMemberBelongsToUserTx {
	return &tenantMemberBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a tenantMemberBelongsToUser) Unscoped() *tenantMemberBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type tenantMemberBelongsToUserTx struct{ tx *gorm.Association }

func (a tenantMemberBelongsToUserTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a tenantMemberBelongsToUserTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a tenantMemberBelongsToUserTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a tenantMemberBelongsToUserTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a tenantMemberBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a tenantMemberBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a tenantMemberBelongsToUserTx) Unscoped() *tenantMemberBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type tenantMemberBelongsToPrimaryDepartment struct {
	db *gorm.DB

	field.RelationField
}

func (a tenantMemberBelongsToPrimaryDepartment) Where(conds ...field.Expr) *tenantMemberBelongsToPrimaryDepartment {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a tenantMemberBelongsToPrimaryDepartment) WithContext(ctx context.Context) *tenantMemberBelongsToPrimaryDepartment {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a tenantMemberBelongsToPrimaryDepartment) Session(session *gorm.Session) *tenantMemberBelongsToPrimaryDepartment {
	a.db = a.db.Session(session)
	return &a
}

func (a tenantMemberBelongsToPrimaryDepartment) Model(m *model.TenantMember) *tenantMemberBelongsToPrimaryDepartmentTx {
	return &tenantMemberBelongsToPrimaryDepartmentTx{a.db.Model(m).Association(a.Name())}
}

func (a tenantMemberBelongsToPrimaryDepartment) Unscoped() *tenantMemberBelongsToPrimaryDepartment {
	a.db = a.db.Unscoped()
	return &a
}

type tenantMemberBelongsToPrimaryDepartmentTx struct{ tx *gorm.Association }

func (a tenantMemberBelongsToPrimaryDepartmentTx) Find() (result *model.Department, err error) {
	return result, a.tx.Find(&result)
}

func (a tenantMemberBelongsToPrimaryDepartmentTx) Append(values ...*model.Department) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a tenantMemberBelongsToPrimaryDepartmentTx) Replace(values ...*model.Department) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a tenantMemberBelongsToPrimaryDepartmentTx) Delete(values ...*model.Department) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a tenantMemberBelongsToPrimaryDepartmentTx) Clear() error {
	return a.tx.Clear()
}

func (a tenantMemberBelongsToPrimaryDepartmentTx) Count() int64 {
	return a.tx.Count()
}

func (a tenantMemberBelongsToPrimaryDepartmentTx) Unscoped() *tenantMemberBelongsToPrimaryDepartmentTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type tenantMemberBelongsToPosition struct {
	db *gorm.DB

	field.RelationField
}

func (a tenantMemberBelongsToPosition) Where(conds ...field.Expr) *tenantMemberBelongsToPosition {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a tenantMemberBelongsToPosition) WithContext(ctx context.Context) *tenantMemberBelongsToPosition {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a tenantMemberBelongsToPosition) Session(session *gorm.Session) *tenantMemberBelongsToPosition {
	a.db = a.db.Session(session)
	return &a
}

func (a tenantMemberBelongsToPosition) Model(m *model.TenantMember) *tenantMemberBelongsToPositionTx {
	return &tenantMemberBelongsToPositionTx{a.db.Model(m).Association(a.Name())}
}

func (a tenantMemberBelongsToPosition) Unscoped() *tenantMemberBelongsToPosition {
	a.db = a.db.Unscoped()
	return &a
}

type tenantMemberBelongsToPositionTx struct{ tx *gorm.Association }

func (a tenantMemberBelongsToPositionTx) Find() (result *model.Position, err error) {
	return result, a.tx.Find(&result)
}

func (a tenantMemberBelongsToPositionTx) Append(values ...*model.Position) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a tenantMemberBelongsToPositionTx) Replace(values ...*model.Position) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a tenantMemberBelongsToPositionTx) Delete(values ...*model.Position) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a tenantMemberBelongsToPositionTx) Clear() error {
	return a.tx.Clear()
}

func (a tenantMemberBelongsToPositionTx) Count() int64 {
	return a.tx.Count()
}

func (a tenantMemberBelongsToPositionTx) Unscoped() *tenantMemberBelongsToPositionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type tenantMemberDo struct{ gen.DO }

type ITenantMemberDo interface {
	gen.SubQuery
	Debug() ITenantMemberDo
	WithContext(ctx context.Context) ITenantMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITenantMemberDo
	WriteDB() ITenantMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITenantMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITenantMemberDo
	Not(conds ...gen.Condition) ITenantMemberDo
	Or(conds ...gen.Condition) ITenantMemberDo
	Select(conds ...field.Expr) ITenantMemberDo
	Where(conds ...gen.Condition) ITenantMemberDo
	Order(conds ...field.Expr) ITenantMemberDo
	Distinct(cols ...field.Expr) ITenantMemberDo
	Omit(cols ...field.Expr) ITenantMemberDo
	Join(table schema.Tabler, on ...field.Expr) ITenantMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITenantMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITenantMemberDo
	Group(cols ...field.Expr) ITenantMemberDo
	Having(conds ...gen.Condition) ITenantMemberDo
	Limit(limit int) ITenantMemberDo
	Offset(offset int) ITenantMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITenantMemberDo
	Unscoped() ITenantMemberDo
	Create(values ...*model.TenantMember) error
	CreateInBatches(values []*model.TenantMember, batchSize int) error
	Save(values ...*model.TenantMember) error
	First() (*model.TenantMember, error)
	Take() (*model.TenantMember, error)
	Last() (*model.TenantMember, error)
	Find() ([]*model.TenantMember, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenantMember, err error)
	FindInBatches(result *[]*model.TenantMember, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TenantMember) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITenantMemberDo
	Assign(attrs ...field.AssignExpr) ITenantMemberDo
	Joins(fields ...field.RelationField) ITenantMemberDo
	Preload(fields ...field.RelationField) ITenantMemberDo
	FirstOrInit() (*model.TenantMember, error)
	FirstOrCreate() (*model.TenantMember, error)
	FindByPage(offset int, limit int) (result []*model.TenantMember, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITenantMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tenantMemberDo) Debug() ITenantMemberDo {
	return t.withDO(t.DO.Debug())
}

func (t tenantMemberDo) WithContext(ctx context.Context) ITenantMemberDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tenantMemberDo) ReadDB() ITenantMemberDo {
	return t.Clauses(dbresolver.Read)
}

func (t tenantMemberDo) WriteDB() ITenantMemberDo {
	return t.Clauses(dbresolver.Write)
}

func (t tenantMemberDo) Session(config *gorm.Session) ITenantMemberDo {
	return t.withDO(t.DO.Session(config))
}

func (t tenantMemberDo) Clauses(conds ...clause.Expression) ITenantMemberDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tenantMemberDo) Returning(value interface{}, columns ...string) ITenantMemberDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tenantMemberDo) Not(conds ...gen.Condition) ITenantMemberDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tenantMemberDo) Or(conds ...gen.Condition) ITenantMemberDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tenantMemberDo) Select(conds ...field.Expr) ITenantMemberDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tenantMemberDo) Where(conds ...gen.Condition) ITenantMemberDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tenantMemberDo) Order(conds ...field.Expr) ITenantMemberDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tenantMemberDo) Distinct(cols ...field.Expr) ITenantMemberDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tenantMemberDo) Omit(cols ...field.Expr) ITenantMemberDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tenantMemberDo) Join(table schema.Tabler, on ...field.Expr) ITenantMemberDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tenantMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITenantMemberDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tenantMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) ITenantMemberDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tenantMemberDo) Group(cols ...field.Expr) ITenantMemberDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tenantMemberDo) Having(conds ...gen.Condition) ITenantMemberDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tenantMemberDo) Limit(limit int) ITenantMemberDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tenantMemberDo) Offset(offset int) ITenantMemberDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tenantMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITenantMemberDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tenantMemberDo) Unscoped() ITenantMemberDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tenantMemberDo) Create(values ...*model.TenantMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tenantMemberDo) CreateInBatches(values []*model.TenantMember, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tenantMemberDo) Save(values ...*model.TenantMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tenantMemberDo) First() (*model.TenantMember, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) Take() (*model.TenantMember, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) Last() (*model.TenantMember, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) Find() ([]*model.TenantMember, error) {
	result, err := t.DO.Find()
	return result.([]*model.TenantMember), err
}

func (t tenantMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenantMember, err error) {
	buf := make([]*model.TenantMember, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tenantMemberDo) FindInBatches(result *[]*model.TenantMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tenantMemberDo) Attrs(attrs ...field.AssignExpr) ITenantMemberDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tenantMemberDo) Assign(attrs ...field.AssignExpr) ITenantMemberDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tenantMemberDo) Joins(fields ...field.RelationField) ITenantMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tenantMemberDo) Preload(fields ...field.RelationField) ITenantMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tenantMemberDo) FirstOrInit() (*model.TenantMember, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) FirstOrCreate() (*model.TenantMember, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) FindByPage(offset int, limit int) (result []*model.TenantMember, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tenantMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tenantMemberDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tenantMemberDo) Delete(models ...*model.TenantMember) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tenantMemberDo) withDO(do gen.Dao) *tenantMemberDo {
	t.DO = *do.(*gen.DO)
	return t
}
