// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/app/admin/internal/data/model"
)

func newTenantAdmin(db *gorm.DB, opts ...gen.DOOption) tenantAdmin {
	_tenantAdmin := tenantAdmin{}

	_tenantAdmin.tenantAdminDo.UseDB(db, opts...)
	_tenantAdmin.tenantAdminDo.UseModel(&model.TenantAdmin{})

	tableName := _tenantAdmin.tenantAdminDo.TableName()
	_tenantAdmin.ALL = field.NewAsterisk(tableName)
	_tenantAdmin.ID = field.NewUint64(tableName, "id")
	_tenantAdmin.TenantID = field.NewUint64(tableName, "tenant_id")
	_tenantAdmin.Username = field.NewString(tableName, "username")
	_tenantAdmin.Email = field.NewString(tableName, "email")
	_tenantAdmin.Phone = field.NewString(tableName, "phone")
	_tenantAdmin.PasswordHash = field.NewString(tableName, "password_hash")
	_tenantAdmin.DisplayName = field.NewString(tableName, "display_name")
	_tenantAdmin.AvatarURL = field.NewString(tableName, "avatar_url")
	_tenantAdmin.MFAEnabled = field.NewBool(tableName, "mfa_enabled")
	_tenantAdmin.MFAChannel = field.NewString(tableName, "mfa_channel")
	_tenantAdmin.Status = field.NewUint8(tableName, "status")
	_tenantAdmin.FailedLoginCount = field.NewUint32(tableName, "failed_login_count")
	_tenantAdmin.LockedUntil = field.NewTime(tableName, "locked_until")
	_tenantAdmin.PasswordChangedAt = field.NewTime(tableName, "password_changed_at")
	_tenantAdmin.CreatedAt = field.NewTime(tableName, "created_at")
	_tenantAdmin.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tenantAdmin.DeletedAt = field.NewField(tableName, "deleted_at")
	_tenantAdmin.Tenant = tenantAdminBelongsToTenant{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Tenant", "model.Tenant"),
	}

	_tenantAdmin.fillFieldMap()

	return _tenantAdmin
}

// tenantAdmin 租户管理员表
type tenantAdmin struct {
	tenantAdminDo tenantAdminDo

	ALL               field.Asterisk
	ID                field.Uint64 // 租户管理员主键
	TenantID          field.Uint64 // 所属租户ID
	Username          field.String // 租户内唯一用户名
	Email             field.String // 租户内邮箱
	Phone             field.String // 租户内手机号
	PasswordHash      field.String // Argon2id密码哈希
	DisplayName       field.String // 显示名称
	AvatarURL         field.String // 头像地址
	MFAEnabled        field.Bool   // 是否启用登录MFA：0否，1是
	MFAChannel        field.String // MFA渠道：email邮件，sms短信
	Status            field.Uint8  // 账号状态：1启用，2禁用，3锁定
	FailedLoginCount  field.Uint32 // 连续登录失败次数
	LockedUntil       field.Time   // 锁定截止时间
	PasswordChangedAt field.Time   // 密码最后修改时间
	CreatedAt         field.Time   // 创建时间
	UpdatedAt         field.Time   // 更新时间
	DeletedAt         field.Field  // 逻辑删除时间
	Tenant            tenantAdminBelongsToTenant

	fieldMap map[string]field.Expr
}

func (t tenantAdmin) Table(newTableName string) *tenantAdmin {
	t.tenantAdminDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tenantAdmin) As(alias string) *tenantAdmin {
	t.tenantAdminDo.DO = *(t.tenantAdminDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tenantAdmin) updateTableName(table string) *tenantAdmin {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint64(table, "id")
	t.TenantID = field.NewUint64(table, "tenant_id")
	t.Username = field.NewString(table, "username")
	t.Email = field.NewString(table, "email")
	t.Phone = field.NewString(table, "phone")
	t.PasswordHash = field.NewString(table, "password_hash")
	t.DisplayName = field.NewString(table, "display_name")
	t.AvatarURL = field.NewString(table, "avatar_url")
	t.MFAEnabled = field.NewBool(table, "mfa_enabled")
	t.MFAChannel = field.NewString(table, "mfa_channel")
	t.Status = field.NewUint8(table, "status")
	t.FailedLoginCount = field.NewUint32(table, "failed_login_count")
	t.LockedUntil = field.NewTime(table, "locked_until")
	t.PasswordChangedAt = field.NewTime(table, "password_changed_at")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tenantAdmin) WithContext(ctx context.Context) ITenantAdminDo {
	return t.tenantAdminDo.WithContext(ctx)
}

func (t tenantAdmin) TableName() string { return t.tenantAdminDo.TableName() }

func (t tenantAdmin) Alias() string { return t.tenantAdminDo.Alias() }

func (t tenantAdmin) Columns(cols ...field.Expr) gen.Columns { return t.tenantAdminDo.Columns(cols...) }

func (t *tenantAdmin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tenantAdmin) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 18)
	t.fieldMap["id"] = t.ID
	t.fieldMap["tenant_id"] = t.TenantID
	t.fieldMap["username"] = t.Username
	t.fieldMap["email"] = t.Email
	t.fieldMap["phone"] = t.Phone
	t.fieldMap["password_hash"] = t.PasswordHash
	t.fieldMap["display_name"] = t.DisplayName
	t.fieldMap["avatar_url"] = t.AvatarURL
	t.fieldMap["mfa_enabled"] = t.MFAEnabled
	t.fieldMap["mfa_channel"] = t.MFAChannel
	t.fieldMap["status"] = t.Status
	t.fieldMap["failed_login_count"] = t.FailedLoginCount
	t.fieldMap["locked_until"] = t.LockedUntil
	t.fieldMap["password_changed_at"] = t.PasswordChangedAt
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt

}

func (t tenantAdmin) clone(db *gorm.DB) tenantAdmin {
	t.tenantAdminDo.ReplaceConnPool(db.Statement.ConnPool)
	t.Tenant.db = db.Session(&gorm.Session{Initialized: true})
	t.Tenant.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t tenantAdmin) replaceDB(db *gorm.DB) tenantAdmin {
	t.tenantAdminDo.ReplaceDB(db)
	t.Tenant.db = db.Session(&gorm.Session{})
	return t
}

type tenantAdminBelongsToTenant struct {
	db *gorm.DB

	field.RelationField
}

func (a tenantAdminBelongsToTenant) Where(conds ...field.Expr) *tenantAdminBelongsToTenant {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a tenantAdminBelongsToTenant) WithContext(ctx context.Context) *tenantAdminBelongsToTenant {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a tenantAdminBelongsToTenant) Session(session *gorm.Session) *tenantAdminBelongsToTenant {
	a.db = a.db.Session(session)
	return &a
}

func (a tenantAdminBelongsToTenant) Model(m *model.TenantAdmin) *tenantAdminBelongsToTenantTx {
	return &tenantAdminBelongsToTenantTx{a.db.Model(m).Association(a.Name())}
}

func (a tenantAdminBelongsToTenant) Unscoped() *tenantAdminBelongsToTenant {
	a.db = a.db.Unscoped()
	return &a
}

type tenantAdminBelongsToTenantTx struct{ tx *gorm.Association }

func (a tenantAdminBelongsToTenantTx) Find() (result *model.Tenant, err error) {
	return result, a.tx.Find(&result)
}

func (a tenantAdminBelongsToTenantTx) Append(values ...*model.Tenant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a tenantAdminBelongsToTenantTx) Replace(values ...*model.Tenant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a tenantAdminBelongsToTenantTx) Delete(values ...*model.Tenant) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a tenantAdminBelongsToTenantTx) Clear() error {
	return a.tx.Clear()
}

func (a tenantAdminBelongsToTenantTx) Count() int64 {
	return a.tx.Count()
}

func (a tenantAdminBelongsToTenantTx) Unscoped() *tenantAdminBelongsToTenantTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type tenantAdminDo struct{ gen.DO }

type ITenantAdminDo interface {
	gen.SubQuery
	Debug() ITenantAdminDo
	WithContext(ctx context.Context) ITenantAdminDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITenantAdminDo
	WriteDB() ITenantAdminDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITenantAdminDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITenantAdminDo
	Not(conds ...gen.Condition) ITenantAdminDo
	Or(conds ...gen.Condition) ITenantAdminDo
	Select(conds ...field.Expr) ITenantAdminDo
	Where(conds ...gen.Condition) ITenantAdminDo
	Order(conds ...field.Expr) ITenantAdminDo
	Distinct(cols ...field.Expr) ITenantAdminDo
	Omit(cols ...field.Expr) ITenantAdminDo
	Join(table schema.Tabler, on ...field.Expr) ITenantAdminDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITenantAdminDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITenantAdminDo
	Group(cols ...field.Expr) ITenantAdminDo
	Having(conds ...gen.Condition) ITenantAdminDo
	Limit(limit int) ITenantAdminDo
	Offset(offset int) ITenantAdminDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITenantAdminDo
	Unscoped() ITenantAdminDo
	Create(values ...*model.TenantAdmin) error
	CreateInBatches(values []*model.TenantAdmin, batchSize int) error
	Save(values ...*model.TenantAdmin) error
	First() (*model.TenantAdmin, error)
	Take() (*model.TenantAdmin, error)
	Last() (*model.TenantAdmin, error)
	Find() ([]*model.TenantAdmin, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenantAdmin, err error)
	FindInBatches(result *[]*model.TenantAdmin, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TenantAdmin) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITenantAdminDo
	Assign(attrs ...field.AssignExpr) ITenantAdminDo
	Joins(fields ...field.RelationField) ITenantAdminDo
	Preload(fields ...field.RelationField) ITenantAdminDo
	FirstOrInit() (*model.TenantAdmin, error)
	FirstOrCreate() (*model.TenantAdmin, error)
	FindByPage(offset int, limit int) (result []*model.TenantAdmin, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITenantAdminDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tenantAdminDo) Debug() ITenantAdminDo {
	return t.withDO(t.DO.Debug())
}

func (t tenantAdminDo) WithContext(ctx context.Context) ITenantAdminDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tenantAdminDo) ReadDB() ITenantAdminDo {
	return t.Clauses(dbresolver.Read)
}

func (t tenantAdminDo) WriteDB() ITenantAdminDo {
	return t.Clauses(dbresolver.Write)
}

func (t tenantAdminDo) Session(config *gorm.Session) ITenantAdminDo {
	return t.withDO(t.DO.Session(config))
}

func (t tenantAdminDo) Clauses(conds ...clause.Expression) ITenantAdminDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tenantAdminDo) Returning(value interface{}, columns ...string) ITenantAdminDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tenantAdminDo) Not(conds ...gen.Condition) ITenantAdminDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tenantAdminDo) Or(conds ...gen.Condition) ITenantAdminDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tenantAdminDo) Select(conds ...field.Expr) ITenantAdminDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tenantAdminDo) Where(conds ...gen.Condition) ITenantAdminDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tenantAdminDo) Order(conds ...field.Expr) ITenantAdminDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tenantAdminDo) Distinct(cols ...field.Expr) ITenantAdminDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tenantAdminDo) Omit(cols ...field.Expr) ITenantAdminDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tenantAdminDo) Join(table schema.Tabler, on ...field.Expr) ITenantAdminDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tenantAdminDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITenantAdminDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tenantAdminDo) RightJoin(table schema.Tabler, on ...field.Expr) ITenantAdminDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tenantAdminDo) Group(cols ...field.Expr) ITenantAdminDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tenantAdminDo) Having(conds ...gen.Condition) ITenantAdminDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tenantAdminDo) Limit(limit int) ITenantAdminDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tenantAdminDo) Offset(offset int) ITenantAdminDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tenantAdminDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITenantAdminDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tenantAdminDo) Unscoped() ITenantAdminDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tenantAdminDo) Create(values ...*model.TenantAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tenantAdminDo) CreateInBatches(values []*model.TenantAdmin, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tenantAdminDo) Save(values ...*model.TenantAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tenantAdminDo) First() (*model.TenantAdmin, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantAdmin), nil
	}
}

func (t tenantAdminDo) Take() (*model.TenantAdmin, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantAdmin), nil
	}
}

func (t tenantAdminDo) Last() (*model.TenantAdmin, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantAdmin), nil
	}
}

func (t tenantAdminDo) Find() ([]*model.TenantAdmin, error) {
	result, err := t.DO.Find()
	return result.([]*model.TenantAdmin), err
}

func (t tenantAdminDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenantAdmin, err error) {
	buf := make([]*model.TenantAdmin, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tenantAdminDo) FindInBatches(result *[]*model.TenantAdmin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tenantAdminDo) Attrs(attrs ...field.AssignExpr) ITenantAdminDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tenantAdminDo) Assign(attrs ...field.AssignExpr) ITenantAdminDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tenantAdminDo) Joins(fields ...field.RelationField) ITenantAdminDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tenantAdminDo) Preload(fields ...field.RelationField) ITenantAdminDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tenantAdminDo) FirstOrInit() (*model.TenantAdmin, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantAdmin), nil
	}
}

func (t tenantAdminDo) FirstOrCreate() (*model.TenantAdmin, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantAdmin), nil
	}
}

func (t tenantAdminDo) FindByPage(offset int, limit int) (result []*model.TenantAdmin, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tenantAdminDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tenantAdminDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tenantAdminDo) Delete(models ...*model.TenantAdmin) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tenantAdminDo) withDO(do gen.Dao) *tenantAdminDo {
	t.DO = *do.(*gen.DO)
	return t
}
