// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	Server        *ServerConfig          `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Data          *DataConfig            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Auth          *AuthConfig            `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	Storage       *StorageConfig         `protobuf:"bytes,5,opt,name=storage,proto3" json:"storage,omitempty"`
	Messaging     *MessagingConfig       `protobuf:"bytes,6,opt,name=messaging,proto3" json:"messaging,omitempty"`
	Setup         *SetupConfig           `protobuf:"bytes,7,opt,name=setup,proto3" json:"setup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Bootstrap) GetServer() *ServerConfig {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *DataConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetStorage() *StorageConfig {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *Bootstrap) GetMessaging() *MessagingConfig {
	if x != nil {
		return x.Messaging
	}
	return nil
}

func (x *Bootstrap) GetSetup() *SetupConfig {
	if x != nil {
		return x.Setup
	}
	return nil
}

type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *ServerConfig_HTTP     `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *ServerConfig_GRPC     `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetHttp() *ServerConfig_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *ServerConfig) GetGrpc() *ServerConfig_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type DataConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DataConfig_Database   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *DataConfig_Redis      `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Rabbitmq      *DataConfig_RabbitMQ   `protobuf:"bytes,3,opt,name=rabbitmq,proto3" json:"rabbitmq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataConfig) Reset() {
	*x = DataConfig{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataConfig) ProtoMessage() {}

func (x *DataConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataConfig.ProtoReflect.Descriptor instead.
func (*DataConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *DataConfig) GetDatabase() *DataConfig_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *DataConfig) GetRedis() *DataConfig_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *DataConfig) GetRabbitmq() *DataConfig_RabbitMQ {
	if x != nil {
		return x.Rabbitmq
	}
	return nil
}

type AuthConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessTtl     *durationpb.Duration   `protobuf:"bytes,1,opt,name=access_ttl,json=accessTtl,proto3" json:"access_ttl,omitempty"`
	RefreshTtl    *durationpb.Duration   `protobuf:"bytes,2,opt,name=refresh_ttl,json=refreshTtl,proto3" json:"refresh_ttl,omitempty"`
	JwtPrivateKey string                 `protobuf:"bytes,3,opt,name=jwt_private_key,json=jwtPrivateKey,proto3" json:"jwt_private_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *AuthConfig) GetAccessTtl() *durationpb.Duration {
	if x != nil {
		return x.AccessTtl
	}
	return nil
}

func (x *AuthConfig) GetRefreshTtl() *durationpb.Duration {
	if x != nil {
		return x.RefreshTtl
	}
	return nil
}

func (x *AuthConfig) GetJwtPrivateKey() string {
	if x != nil {
		return x.JwtPrivateKey
	}
	return ""
}

func (x *AuthConfig) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type StorageConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Provider           string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	LocalPath          string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	MaxFileSize        int64                  `protobuf:"varint,3,opt,name=max_file_size,json=maxFileSize,proto3" json:"max_file_size,omitempty"`
	OssRegion          string                 `protobuf:"bytes,4,opt,name=oss_region,json=ossRegion,proto3" json:"oss_region,omitempty"`
	OssEndpoint        string                 `protobuf:"bytes,5,opt,name=oss_endpoint,json=ossEndpoint,proto3" json:"oss_endpoint,omitempty"`
	OssBucket          string                 `protobuf:"bytes,6,opt,name=oss_bucket,json=ossBucket,proto3" json:"oss_bucket,omitempty"`
	OssAccessKeyId     string                 `protobuf:"bytes,7,opt,name=oss_access_key_id,json=ossAccessKeyId,proto3" json:"oss_access_key_id,omitempty"`
	OssAccessKeySecret string                 `protobuf:"bytes,8,opt,name=oss_access_key_secret,json=ossAccessKeySecret,proto3" json:"oss_access_key_secret,omitempty"`
	OssSecurityToken   string                 `protobuf:"bytes,9,opt,name=oss_security_token,json=ossSecurityToken,proto3" json:"oss_security_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StorageConfig) Reset() {
	*x = StorageConfig{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConfig) ProtoMessage() {}

func (x *StorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConfig.ProtoReflect.Descriptor instead.
func (*StorageConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *StorageConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StorageConfig) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *StorageConfig) GetMaxFileSize() int64 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *StorageConfig) GetOssRegion() string {
	if x != nil {
		return x.OssRegion
	}
	return ""
}

func (x *StorageConfig) GetOssEndpoint() string {
	if x != nil {
		return x.OssEndpoint
	}
	return ""
}

func (x *StorageConfig) GetOssBucket() string {
	if x != nil {
		return x.OssBucket
	}
	return ""
}

func (x *StorageConfig) GetOssAccessKeyId() string {
	if x != nil {
		return x.OssAccessKeyId
	}
	return ""
}

func (x *StorageConfig) GetOssAccessKeySecret() string {
	if x != nil {
		return x.OssAccessKeySecret
	}
	return ""
}

func (x *StorageConfig) GetOssSecurityToken() string {
	if x != nil {
		return x.OssSecurityToken
	}
	return ""
}

type MessagingConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SmtpAddress              string                 `protobuf:"bytes,1,opt,name=smtp_address,json=smtpAddress,proto3" json:"smtp_address,omitempty"`
	SmtpHost                 string                 `protobuf:"bytes,2,opt,name=smtp_host,json=smtpHost,proto3" json:"smtp_host,omitempty"`
	SmtpUsername             string                 `protobuf:"bytes,3,opt,name=smtp_username,json=smtpUsername,proto3" json:"smtp_username,omitempty"`
	SmtpPassword             string                 `protobuf:"bytes,4,opt,name=smtp_password,json=smtpPassword,proto3" json:"smtp_password,omitempty"`
	SmtpFrom                 string                 `protobuf:"bytes,5,opt,name=smtp_from,json=smtpFrom,proto3" json:"smtp_from,omitempty"`
	SmtpUseTls               bool                   `protobuf:"varint,6,opt,name=smtp_use_tls,json=smtpUseTls,proto3" json:"smtp_use_tls,omitempty"`
	AliyunSmsRegion          string                 `protobuf:"bytes,7,opt,name=aliyun_sms_region,json=aliyunSmsRegion,proto3" json:"aliyun_sms_region,omitempty"`
	AliyunSmsEndpoint        string                 `protobuf:"bytes,8,opt,name=aliyun_sms_endpoint,json=aliyunSmsEndpoint,proto3" json:"aliyun_sms_endpoint,omitempty"`
	AliyunSmsAccessKeyId     string                 `protobuf:"bytes,9,opt,name=aliyun_sms_access_key_id,json=aliyunSmsAccessKeyId,proto3" json:"aliyun_sms_access_key_id,omitempty"`
	AliyunSmsAccessKeySecret string                 `protobuf:"bytes,10,opt,name=aliyun_sms_access_key_secret,json=aliyunSmsAccessKeySecret,proto3" json:"aliyun_sms_access_key_secret,omitempty"`
	AliyunSmsSignName        string                 `protobuf:"bytes,11,opt,name=aliyun_sms_sign_name,json=aliyunSmsSignName,proto3" json:"aliyun_sms_sign_name,omitempty"`
	AliyunSmsTemplateCode    string                 `protobuf:"bytes,12,opt,name=aliyun_sms_template_code,json=aliyunSmsTemplateCode,proto3" json:"aliyun_sms_template_code,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MessagingConfig) Reset() {
	*x = MessagingConfig{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagingConfig) ProtoMessage() {}

func (x *MessagingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagingConfig.ProtoReflect.Descriptor instead.
func (*MessagingConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *MessagingConfig) GetSmtpAddress() string {
	if x != nil {
		return x.SmtpAddress
	}
	return ""
}

func (x *MessagingConfig) GetSmtpHost() string {
	if x != nil {
		return x.SmtpHost
	}
	return ""
}

func (x *MessagingConfig) GetSmtpUsername() string {
	if x != nil {
		return x.SmtpUsername
	}
	return ""
}

func (x *MessagingConfig) GetSmtpPassword() string {
	if x != nil {
		return x.SmtpPassword
	}
	return ""
}

func (x *MessagingConfig) GetSmtpFrom() string {
	if x != nil {
		return x.SmtpFrom
	}
	return ""
}

func (x *MessagingConfig) GetSmtpUseTls() bool {
	if x != nil {
		return x.SmtpUseTls
	}
	return false
}

func (x *MessagingConfig) GetAliyunSmsRegion() string {
	if x != nil {
		return x.AliyunSmsRegion
	}
	return ""
}

func (x *MessagingConfig) GetAliyunSmsEndpoint() string {
	if x != nil {
		return x.AliyunSmsEndpoint
	}
	return ""
}

func (x *MessagingConfig) GetAliyunSmsAccessKeyId() string {
	if x != nil {
		return x.AliyunSmsAccessKeyId
	}
	return ""
}

func (x *MessagingConfig) GetAliyunSmsAccessKeySecret() string {
	if x != nil {
		return x.AliyunSmsAccessKeySecret
	}
	return ""
}

func (x *MessagingConfig) GetAliyunSmsSignName() string {
	if x != nil {
		return x.AliyunSmsSignName
	}
	return ""
}

func (x *MessagingConfig) GetAliyunSmsTemplateCode() string {
	if x != nil {
		return x.AliyunSmsTemplateCode
	}
	return ""
}

type SetupConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *SetupConfig_Admin     `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupConfig) Reset() {
	*x = SetupConfig{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupConfig) ProtoMessage() {}

func (x *SetupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupConfig.ProtoReflect.Descriptor instead.
func (*SetupConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *SetupConfig) GetAdmin() *SetupConfig_Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type ServerConfig_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig_HTTP) Reset() {
	*x = ServerConfig_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig_HTTP) ProtoMessage() {}

func (x *ServerConfig_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig_HTTP.ProtoReflect.Descriptor instead.
func (*ServerConfig_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServerConfig_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ServerConfig_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServerConfig_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ServerConfig_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig_GRPC) Reset() {
	*x = ServerConfig_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig_GRPC) ProtoMessage() {}

func (x *ServerConfig_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig_GRPC.ProtoReflect.Descriptor instead.
func (*ServerConfig_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ServerConfig_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ServerConfig_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServerConfig_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type DataConfig_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	MigrationsDir string                 `protobuf:"bytes,3,opt,name=migrations_dir,json=migrationsDir,proto3" json:"migrations_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataConfig_Database) Reset() {
	*x = DataConfig_Database{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataConfig_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataConfig_Database) ProtoMessage() {}

func (x *DataConfig_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataConfig_Database.ProtoReflect.Descriptor instead.
func (*DataConfig_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DataConfig_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DataConfig_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DataConfig_Database) GetMigrationsDir() string {
	if x != nil {
		return x.MigrationsDir
	}
	return ""
}

type DataConfig_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,4,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,5,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataConfig_Redis) Reset() {
	*x = DataConfig_Redis{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataConfig_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataConfig_Redis) ProtoMessage() {}

func (x *DataConfig_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataConfig_Redis.ProtoReflect.Descriptor instead.
func (*DataConfig_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *DataConfig_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DataConfig_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *DataConfig_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *DataConfig_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *DataConfig_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

type DataConfig_RabbitMQ struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Prefetch      int32                  `protobuf:"varint,2,opt,name=prefetch,proto3" json:"prefetch,omitempty"`
	Concurrency   int32                  `protobuf:"varint,3,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataConfig_RabbitMQ) Reset() {
	*x = DataConfig_RabbitMQ{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataConfig_RabbitMQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataConfig_RabbitMQ) ProtoMessage() {}

func (x *DataConfig_RabbitMQ) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataConfig_RabbitMQ.ProtoReflect.Descriptor instead.
func (*DataConfig_RabbitMQ) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *DataConfig_RabbitMQ) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DataConfig_RabbitMQ) GetPrefetch() int32 {
	if x != nil {
		return x.Prefetch
	}
	return 0
}

func (x *DataConfig_RabbitMQ) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type SetupConfig_Admin struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Username        string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone           string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	InitialPassword string                 `protobuf:"bytes,5,opt,name=initial_password,json=initialPassword,proto3" json:"initial_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetupConfig_Admin) Reset() {
	*x = SetupConfig_Admin{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupConfig_Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupConfig_Admin) ProtoMessage() {}

func (x *SetupConfig_Admin) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupConfig_Admin.ProtoReflect.Descriptor instead.
func (*SetupConfig_Admin) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SetupConfig_Admin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SetupConfig_Admin) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SetupConfig_Admin) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetupConfig_Admin) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SetupConfig_Admin) GetInitialPassword() string {
	if x != nil {
		return x.InitialPassword
	}
	return ""
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\x11kratos.admin.conf\x1a\x1egoogle/protobuf/duration.proto\"\x80\x03\n" +
	"\tBootstrap\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x127\n" +
	"\x06server\x18\x02 \x01(\v2\x1f.kratos.admin.conf.ServerConfigR\x06server\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.kratos.admin.conf.DataConfigR\x04data\x121\n" +
	"\x04auth\x18\x04 \x01(\v2\x1d.kratos.admin.conf.AuthConfigR\x04auth\x12:\n" +
	"\astorage\x18\x05 \x01(\v2 .kratos.admin.conf.StorageConfigR\astorage\x12@\n" +
	"\tmessaging\x18\x06 \x01(\v2\".kratos.admin.conf.MessagingConfigR\tmessaging\x124\n" +
	"\x05setup\x18\a \x01(\v2\x1e.kratos.admin.conf.SetupConfigR\x05setup\"\xd8\x02\n" +
	"\fServerConfig\x128\n" +
	"\x04http\x18\x01 \x01(\v2$.kratos.admin.conf.ServerConfig.HTTPR\x04http\x128\n" +
	"\x04grpc\x18\x02 \x01(\v2$.kratos.admin.conf.ServerConfig.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xd4\x04\n" +
	"\n" +
	"DataConfig\x12B\n" +
	"\bdatabase\x18\x01 \x01(\v2&.kratos.admin.conf.DataConfig.DatabaseR\bdatabase\x129\n" +
	"\x05redis\x18\x02 \x01(\v2#.kratos.admin.conf.DataConfig.RedisR\x05redis\x12B\n" +
	"\brabbitmq\x18\x03 \x01(\v2&.kratos.admin.conf.DataConfig.RabbitMQR\brabbitmq\x1aa\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12%\n" +
	"\x0emigrations_dir\x18\x03 \x01(\tR\rmigrationsDir\x1a\xc3\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\x12<\n" +
	"\fread_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x1aZ\n" +
	"\bRabbitMQ\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bprefetch\x18\x02 \x01(\x05R\bprefetch\x12 \n" +
	"\vconcurrency\x18\x03 \x01(\x05R\vconcurrency\"\xc9\x01\n" +
	"\n" +
	"AuthConfig\x128\n" +
	"\n" +
	"access_ttl\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\taccessTtl\x12:\n" +
	"\vrefresh_ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"refreshTtl\x12&\n" +
	"\x0fjwt_private_key\x18\x03 \x01(\tR\rjwtPrivateKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\"\xdb\x02\n" +
	"\rStorageConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\x12\"\n" +
	"\rmax_file_size\x18\x03 \x01(\x03R\vmaxFileSize\x12\x1d\n" +
	"\n" +
	"oss_region\x18\x04 \x01(\tR\tossRegion\x12!\n" +
	"\foss_endpoint\x18\x05 \x01(\tR\vossEndpoint\x12\x1d\n" +
	"\n" +
	"oss_bucket\x18\x06 \x01(\tR\tossBucket\x12)\n" +
	"\x11oss_access_key_id\x18\a \x01(\tR\x0eossAccessKeyId\x121\n" +
	"\x15oss_access_key_secret\x18\b \x01(\tR\x12ossAccessKeySecret\x12,\n" +
	"\x12oss_security_token\x18\t \x01(\tR\x10ossSecurityToken\"\x98\x04\n" +
	"\x0fMessagingConfig\x12!\n" +
	"\fsmtp_address\x18\x01 \x01(\tR\vsmtpAddress\x12\x1b\n" +
	"\tsmtp_host\x18\x02 \x01(\tR\bsmtpHost\x12#\n" +
	"\rsmtp_username\x18\x03 \x01(\tR\fsmtpUsername\x12#\n" +
	"\rsmtp_password\x18\x04 \x01(\tR\fsmtpPassword\x12\x1b\n" +
	"\tsmtp_from\x18\x05 \x01(\tR\bsmtpFrom\x12 \n" +
	"\fsmtp_use_tls\x18\x06 \x01(\bR\n" +
	"smtpUseTls\x12*\n" +
	"\x11aliyun_sms_region\x18\a \x01(\tR\x0faliyunSmsRegion\x12.\n" +
	"\x13aliyun_sms_endpoint\x18\b \x01(\tR\x11aliyunSmsEndpoint\x126\n" +
	"\x18aliyun_sms_access_key_id\x18\t \x01(\tR\x14aliyunSmsAccessKeyId\x12>\n" +
	"\x1caliyun_sms_access_key_secret\x18\n" +
	" \x01(\tR\x18aliyunSmsAccessKeySecret\x12/\n" +
	"\x14aliyun_sms_sign_name\x18\v \x01(\tR\x11aliyunSmsSignName\x127\n" +
	"\x18aliyun_sms_template_code\x18\f \x01(\tR\x15aliyunSmsTemplateCode\"\xe9\x01\n" +
	"\vSetupConfig\x12:\n" +
	"\x05admin\x18\x01 \x01(\v2$.kratos.admin.conf.SetupConfig.AdminR\x05admin\x1a\x9d\x01\n" +
	"\x05Admin\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12)\n" +
	"\x10initial_password\x18\x05 \x01(\tR\x0finitialPasswordB5Z3github.com/sleep-go/kratos-admin/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.admin.conf.Bootstrap
	(*ServerConfig)(nil),        // 1: kratos.admin.conf.ServerConfig
	(*DataConfig)(nil),          // 2: kratos.admin.conf.DataConfig
	(*AuthConfig)(nil),          // 3: kratos.admin.conf.AuthConfig
	(*StorageConfig)(nil),       // 4: kratos.admin.conf.StorageConfig
	(*MessagingConfig)(nil),     // 5: kratos.admin.conf.MessagingConfig
	(*SetupConfig)(nil),         // 6: kratos.admin.conf.SetupConfig
	(*ServerConfig_HTTP)(nil),   // 7: kratos.admin.conf.ServerConfig.HTTP
	(*ServerConfig_GRPC)(nil),   // 8: kratos.admin.conf.ServerConfig.GRPC
	(*DataConfig_Database)(nil), // 9: kratos.admin.conf.DataConfig.Database
	(*DataConfig_Redis)(nil),    // 10: kratos.admin.conf.DataConfig.Redis
	(*DataConfig_RabbitMQ)(nil), // 11: kratos.admin.conf.DataConfig.RabbitMQ
	(*SetupConfig_Admin)(nil),   // 12: kratos.admin.conf.SetupConfig.Admin
	(*durationpb.Duration)(nil), // 13: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.admin.conf.Bootstrap.server:type_name -> kratos.admin.conf.ServerConfig
	2,  // 1: kratos.admin.conf.Bootstrap.data:type_name -> kratos.admin.conf.DataConfig
	3,  // 2: kratos.admin.conf.Bootstrap.auth:type_name -> kratos.admin.conf.AuthConfig
	4,  // 3: kratos.admin.conf.Bootstrap.storage:type_name -> kratos.admin.conf.StorageConfig
	5,  // 4: kratos.admin.conf.Bootstrap.messaging:type_name -> kratos.admin.conf.MessagingConfig
	6,  // 5: kratos.admin.conf.Bootstrap.setup:type_name -> kratos.admin.conf.SetupConfig
	7,  // 6: kratos.admin.conf.ServerConfig.http:type_name -> kratos.admin.conf.ServerConfig.HTTP
	8,  // 7: kratos.admin.conf.ServerConfig.grpc:type_name -> kratos.admin.conf.ServerConfig.GRPC
	9,  // 8: kratos.admin.conf.DataConfig.database:type_name -> kratos.admin.conf.DataConfig.Database
	10, // 9: kratos.admin.conf.DataConfig.redis:type_name -> kratos.admin.conf.DataConfig.Redis
	11, // 10: kratos.admin.conf.DataConfig.rabbitmq:type_name -> kratos.admin.conf.DataConfig.RabbitMQ
	13, // 11: kratos.admin.conf.AuthConfig.access_ttl:type_name -> google.protobuf.Duration
	13, // 12: kratos.admin.conf.AuthConfig.refresh_ttl:type_name -> google.protobuf.Duration
	12, // 13: kratos.admin.conf.SetupConfig.admin:type_name -> kratos.admin.conf.SetupConfig.Admin
	13, // 14: kratos.admin.conf.ServerConfig.HTTP.timeout:type_name -> google.protobuf.Duration
	13, // 15: kratos.admin.conf.ServerConfig.GRPC.timeout:type_name -> google.protobuf.Duration
	13, // 16: kratos.admin.conf.DataConfig.Redis.read_timeout:type_name -> google.protobuf.Duration
	13, // 17: kratos.admin.conf.DataConfig.Redis.write_timeout:type_name -> google.protobuf.Duration
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
