// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dps/internal/biz"
	"dps/internal/conf"
	"dps/internal/data"
	"dps/internal/server"
	"dps/internal/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	adminRepo := data.NewAdminRepo(dataData)
	adminUsecase := biz.NewAdminUsecase(adminRepo)
	adminService := service.NewAdminService(adminUsecase)
	grpcServer := server.NewGRPCServer(confServer, adminService)
	httpServer := server.NewHTTPServer(confServer, adminService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
