// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameAPIAccessLog = "api_access_logs"

// APIAccessLog API访问与异常日志表
type APIAccessLog struct {
	ID          uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:API访问日志主键" json:"id"`                                                                                                  // API访问日志主键
	TenantID    uint64         `gorm:"column:tenant_id;type:bigint unsigned;not null;index:idx_api_access_logs_error,priority:1;index:idx_api_access_logs_query,priority:1;default:0;comment:所属租户ID，0表示未认证或平台域" json:"tenant_id"` // 所属租户ID，0表示未认证或平台域
	UserID      uint64         `gorm:"column:user_id;type:bigint unsigned;not null;default:0;comment:用户ID，未认证为0" json:"user_id"`                                                                                                  // 用户ID，未认证为0
	RequestID   string         `gorm:"column:request_id;type:varchar(64);not null;index:idx_api_access_logs_request,priority:1;comment:请求追踪ID" json:"request_id"`                                                                 // 请求追踪ID
	Method      string         `gorm:"column:method;type:varchar(16);not null;comment:HTTP方法" json:"method"`                                                                                                                      // HTTP方法
	Route       string         `gorm:"column:route;type:varchar(255);not null;comment:HTTP路由模板" json:"route"`                                                                                                                     // HTTP路由模板
	StatusCode  uint16         `gorm:"column:status_code;type:smallint unsigned;not null;index:idx_api_access_logs_error,priority:2;comment:HTTP响应状态码" json:"status_code"`                                                        // HTTP响应状态码
	DurationMS  uint32         `gorm:"column:duration_ms;type:int unsigned;not null;comment:请求耗时毫秒" json:"duration_ms"`                                                                                                           // 请求耗时毫秒
	IP          string         `gorm:"column:ip;type:varchar(64);not null;comment:客户端IP" json:"ip"`                                                                                                                               // 客户端IP
	UserAgent   string         `gorm:"column:user_agent;type:varchar(512);not null;comment:客户端User-Agent" json:"user_agent"`                                                                                                      // 客户端User-Agent
	RequestData datatypes.JSON `gorm:"column:request_data;type:json;comment:白名单脱敏请求数据" json:"request_data"`                                                                                                                       // 白名单脱敏请求数据
	ErrorReason string         `gorm:"column:error_reason;type:varchar(128);not null;comment:业务错误原因" json:"error_reason"`                                                                                                         // 业务错误原因
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime(3);not null;index:idx_api_access_logs_error,priority:3;index:idx_api_access_logs_query,priority:2;comment:发生时间" json:"created_at"`                          // 发生时间
}

// TableName APIAccessLog's table name
func (*APIAccessLog) TableName() string {
	return TableNameAPIAccessLog
}
