// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDictionaryItem = "dictionary_items"

// DictionaryItem 参数字典项表
type DictionaryItem struct {
	ID        uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:字典项主键" json:"id"`                                                                                                         // 字典项主键
	TenantID  uint64         `gorm:"column:tenant_id;type:bigint unsigned;not null;uniqueIndex:uk_dictionary_items_value,priority:1;index:idx_dictionary_items_type,priority:1;default:0;comment:所属租户ID，0表示平台字典" json:"tenant_id"` // 所属租户ID，0表示平台字典
	TypeID    uint64         `gorm:"column:type_id;type:bigint unsigned;not null;uniqueIndex:uk_dictionary_items_value,priority:2;index:idx_dictionary_items_type,priority:2;comment:字典类型ID" json:"type_id"`                       // 字典类型ID
	ItemValue string         `gorm:"column:item_value;type:varchar(191);not null;uniqueIndex:uk_dictionary_items_value,priority:3;comment:字典项值" json:"item_value"`                                                                 // 字典项值
	Label     string         `gorm:"column:label;type:varchar(128);not null;comment:字典项显示名称" json:"label"`                                                                                                                         // 字典项显示名称
	SortOrder int32          `gorm:"column:sort_order;type:int;not null;default:0;comment:显示排序值" json:"sort_order"`                                                                                                                // 显示排序值
	Status    uint8          `gorm:"column:status;type:tinyint unsigned;not null;index:idx_dictionary_items_type,priority:3;default:1;comment:字典项状态：1启用，2禁用" json:"status"`                                                        // 字典项状态：1启用，2禁用
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null;comment:创建时间" json:"created_at"`                                                                                                                   // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null;comment:更新时间" json:"updated_at"`                                                                                                                   // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_dictionary_items_type,priority:4;comment:逻辑删除时间" json:"deleted_at"`                                                                               // 逻辑删除时间
}

// TableName DictionaryItem's table name
func (*DictionaryItem) TableName() string {
	return TableNameDictionaryItem
}
