// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosition = "positions"

// Position 岗位表
type Position struct {
	ID        uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:岗位主键" json:"id"`                                                                                         // 岗位主键
	TenantID  uint64         `gorm:"column:tenant_id;type:bigint unsigned;not null;uniqueIndex:uk_positions_tenant_code,priority:1;index:idx_positions_tenant_status,priority:1;comment:所属租户ID" json:"tenant_id"` // 所属租户ID
	Code      string         `gorm:"column:code;type:varchar(64);not null;uniqueIndex:uk_positions_tenant_code,priority:2;comment:租户内唯一岗位编码" json:"code"`                                                         // 租户内唯一岗位编码
	Name      string         `gorm:"column:name;type:varchar(128);not null;comment:岗位名称" json:"name"`                                                                                                             // 岗位名称
	SortOrder int32          `gorm:"column:sort_order;type:int;not null;default:0;comment:显示排序值" json:"sort_order"`                                                                                               // 显示排序值
	Status    uint8          `gorm:"column:status;type:tinyint unsigned;not null;index:idx_positions_tenant_status,priority:2;default:1;comment:岗位状态：1启用，2禁用" json:"status"`                                      // 岗位状态：1启用，2禁用
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null;comment:创建时间" json:"created_at"`                                                                                                  // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null;comment:更新时间" json:"updated_at"`                                                                                                  // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_positions_tenant_status,priority:3;comment:逻辑删除时间" json:"deleted_at"`                                                            // 逻辑删除时间
}

// TableName Position's table name
func (*Position) TableName() string {
	return TableNamePosition
}
