// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProviderConfig = "provider_configs"

// ProviderConfig 邮件短信与存储Provider配置表
type ProviderConfig struct {
	ID              uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:Provider配置主键" json:"id"`                                                                                                                          // Provider配置主键
	TenantID        uint64    `gorm:"column:tenant_id;type:bigint unsigned;not null;uniqueIndex:uk_provider_configs_scope_name,priority:1;index:idx_provider_configs_default,priority:1;default:0;comment:配置租户ID，0表示平台默认" json:"tenant_id"`                 // 配置租户ID，0表示平台默认
	ProviderType    string    `gorm:"column:provider_type;type:varchar(32);not null;uniqueIndex:uk_provider_configs_scope_name,priority:2;index:idx_provider_configs_default,priority:2;comment:Provider类型：email邮件，sms短信，storage对象存储" json:"provider_type"` // Provider类型：email邮件，sms短信，storage对象存储
	ProviderName    string    `gorm:"column:provider_name;type:varchar(64);not null;uniqueIndex:uk_provider_configs_scope_name,priority:3;comment:Provider实现名称" json:"provider_name"`                                                                       // Provider实现名称
	DisplayName     string    `gorm:"column:display_name;type:varchar(128);not null;comment:配置显示名称" json:"display_name"`                                                                                                                                    // 配置显示名称
	EncryptedConfig string    `gorm:"column:encrypted_config;type:text;not null;comment:主密钥加密后的Provider配置" json:"encrypted_config"`                                                                                                                         // 主密钥加密后的Provider配置
	Status          uint8     `gorm:"column:status;type:tinyint unsigned;not null;index:idx_provider_configs_default,priority:4;default:1;comment:配置状态：1启用，2禁用" json:"status"`                                                                              // 配置状态：1启用，2禁用
	IsDefault       bool      `gorm:"column:is_default;type:tinyint(1);not null;index:idx_provider_configs_default,priority:3;default:0;comment:是否作用域默认：0否，1是" json:"is_default"`                                                                           // 是否作用域默认：0否，1是
	UpdatedBy       uint64    `gorm:"column:updated_by;type:bigint unsigned;not null;default:0;comment:最后更新用户ID" json:"updated_by"`                                                                                                                         // 最后更新用户ID
	CreatedAt       time.Time `gorm:"column:created_at;type:datetime(3);not null;comment:创建时间" json:"created_at"`                                                                                                                                           // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;type:datetime(3);not null;comment:更新时间" json:"updated_at"`                                                                                                                                           // 更新时间
}

// TableName ProviderConfig's table name
func (*ProviderConfig) TableName() string {
	return TableNameProviderConfig
}
