// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameResource = "resources"

// Resource 菜单与权限资源表
type Resource struct {
	ID           uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:权限资源主键" json:"id"`                                                // 权限资源主键
	ParentID     uint64         `gorm:"column:parent_id;type:bigint unsigned;not null;index:idx_resources_parent,priority:1;default:0;comment:父资源ID，0表示根资源" json:"parent_id"` // 父资源ID，0表示根资源
	Type         uint8          `gorm:"column:type;type:tinyint unsigned;not null;index:idx_resources_parent,priority:2;comment:资源类型：1目录，2菜单，3按钮，4API" json:"type"`           // 资源类型：1目录，2菜单，3按钮，4API
	ScopeMask    uint8          `gorm:"column:scope_mask;type:tinyint unsigned;not null;default:3;comment:资源适用范围位标记：1仅平台，2仅租户，3平台与租户共用" json:"scope_mask"`                    // 资源适用范围位标记：1仅平台，2仅租户，3平台与租户共用
	Code         string         `gorm:"column:code;type:varchar(128);not null;uniqueIndex:uk_resources_code,priority:1;comment:全局唯一资源编码" json:"code"`                         // 全局唯一资源编码
	Name         string         `gorm:"column:name;type:varchar(128);not null;comment:资源名称" json:"name"`                                                                      // 资源名称
	RoutePath    string         `gorm:"column:route_path;type:varchar(255);not null;comment:前端路由路径" json:"route_path"`                                                        // 前端路由路径
	ComponentKey string         `gorm:"column:component_key;type:varchar(128);not null;comment:前端预注册组件键" json:"component_key"`                                                // 前端预注册组件键
	HTTPMethod   string         `gorm:"column:http_method;type:varchar(16);not null;comment:API资源HTTP方法" json:"http_method"`                                                  // API资源HTTP方法
	APIPath      string         `gorm:"column:api_path;type:varchar(255);not null;comment:API资源路由模板" json:"api_path"`                                                         // API资源路由模板
	Icon         string         `gorm:"column:icon;type:varchar(64);not null;comment:前端图标名称" json:"icon"`                                                                     // 前端图标名称
	SortOrder    int32          `gorm:"column:sort_order;type:int;not null;default:0;comment:显示排序值" json:"sort_order"`                                                        // 显示排序值
	Visible      bool           `gorm:"column:visible;type:tinyint(1);not null;default:1;comment:是否显示：0隐藏，1显示" json:"visible"`                                                // 是否显示：0隐藏，1显示
	Status       uint8          `gorm:"column:status;type:tinyint unsigned;not null;index:idx_resources_parent,priority:3;default:1;comment:资源状态：1启用，2禁用" json:"status"`      // 资源状态：1启用，2禁用
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime(3);not null;comment:创建时间" json:"created_at"`                                                           // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime(3);not null;comment:更新时间" json:"updated_at"`                                                           // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_resources_parent,priority:4;comment:逻辑删除时间" json:"deleted_at"`                            // 逻辑删除时间
}

// TableName Resource's table name
func (*Resource) TableName() string {
	return TableNameResource
}
