// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameSystemSetting = "system_settings"

// SystemSetting 平台与租户系统配置表
type SystemSetting struct {
	ID                  uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:系统配置主键" json:"id"`                                                                // 系统配置主键
	TenantID            uint64         `gorm:"column:tenant_id;type:bigint unsigned;not null;uniqueIndex:uk_system_settings_scope_key,priority:1;default:0;comment:配置租户ID，0表示平台默认" json:"tenant_id"` // 配置租户ID，0表示平台默认
	Category            string         `gorm:"column:category;type:varchar(64);not null;uniqueIndex:uk_system_settings_scope_key,priority:2;comment:配置分类" json:"category"`                           // 配置分类
	SettingKey          string         `gorm:"column:setting_key;type:varchar(128);not null;uniqueIndex:uk_system_settings_scope_key,priority:3;comment:配置键" json:"setting_key"`                     // 配置键
	ValueType           string         `gorm:"column:value_type;type:varchar(16);not null;comment:值类型：string字符串，number数字，boolean布尔，json对象" json:"value_type"`                                        // 值类型：string字符串，number数字，boolean布尔，json对象
	SettingValue        datatypes.JSON `gorm:"column:setting_value;type:json;not null;comment:配置值" json:"setting_value"`                                                                             // 配置值
	AllowTenantOverride bool           `gorm:"column:allow_tenant_override;type:tinyint(1);not null;default:0;comment:是否允许租户覆盖：0否，1是" json:"allow_tenant_override"`                                  // 是否允许租户覆盖：0否，1是
	IsSecret            bool           `gorm:"column:is_secret;type:tinyint(1);not null;default:0;comment:是否敏感配置：0否，1是" json:"is_secret"`                                                            // 是否敏感配置：0否，1是
	Version             uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1;comment:配置版本号" json:"version"`                                                                  // 配置版本号
	UpdatedBy           uint64         `gorm:"column:updated_by;type:bigint unsigned;not null;default:0;comment:最后更新用户ID" json:"updated_by"`                                                         // 最后更新用户ID
	CreatedAt           time.Time      `gorm:"column:created_at;type:datetime(3);not null;comment:创建时间" json:"created_at"`                                                                           // 创建时间
	UpdatedAt           time.Time      `gorm:"column:updated_at;type:datetime(3);not null;comment:更新时间" json:"updated_at"`                                                                           // 更新时间
}

// TableName SystemSetting's table name
func (*SystemSetting) TableName() string {
	return TableNameSystemSetting
}
