// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTenantMember = "tenant_members"

// TenantMember 租户成员表
type TenantMember struct {
	ID                  uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:租户成员主键" json:"id"`                                                                                              // 租户成员主键
	TenantID            uint64         `gorm:"column:tenant_id;type:bigint unsigned;not null;uniqueIndex:uk_tenant_members_tenant_user,priority:1;index:idx_tenant_members_department,priority:1;comment:所属租户ID" json:"tenant_id"` // 所属租户ID
	UserID              uint64         `gorm:"column:user_id;type:bigint unsigned;not null;uniqueIndex:uk_tenant_members_tenant_user,priority:2;index:idx_tenant_members_user,priority:1;comment:关联全局用户ID" json:"user_id"`         // 关联全局用户ID
	PrimaryDepartmentID uint64         `gorm:"column:primary_department_id;type:bigint unsigned;not null;index:idx_tenant_members_department,priority:2;default:0;comment:主部门ID，0表示未分配" json:"primary_department_id"`              // 主部门ID，0表示未分配
	PositionID          uint64         `gorm:"column:position_id;type:bigint unsigned;not null;default:0;comment:岗位ID，0表示未分配" json:"position_id"`                                                                                  // 岗位ID，0表示未分配
	DisplayName         string         `gorm:"column:display_name;type:varchar(128);not null;comment:租户内显示名称" json:"display_name"`                                                                                                 // 租户内显示名称
	Status              uint8          `gorm:"column:status;type:tinyint unsigned;not null;index:idx_tenant_members_user,priority:2;default:1;comment:成员状态：1启用，2禁用" json:"status"`                                                 // 成员状态：1启用，2禁用
	IsTenantAdmin       bool           `gorm:"column:is_tenant_admin;type:tinyint(1);not null;default:0;comment:是否租户管理员：0否，1是" json:"is_tenant_admin"`                                                                             // 是否租户管理员：0否，1是
	JoinedAt            time.Time      `gorm:"column:joined_at;type:datetime(3);not null;default:CURRENT_TIMESTAMP(3);comment:加入租户时间" json:"joined_at"`                                                                            // 加入租户时间
	CreatedAt           time.Time      `gorm:"column:created_at;type:datetime(3);not null;comment:创建时间" json:"created_at"`                                                                                                         // 创建时间
	UpdatedAt           time.Time      `gorm:"column:updated_at;type:datetime(3);not null;comment:更新时间" json:"updated_at"`                                                                                                         // 更新时间
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_tenant_members_department,priority:3;index:idx_tenant_members_user,priority:3;comment:逻辑删除时间" json:"deleted_at"`                        // 逻辑删除时间
	User                *User          `gorm:"foreignKey:UserID;references:ID" json:"user"`
	PrimaryDepartment   *Department    `gorm:"foreignKey:PrimaryDepartmentID;references:ID" json:"primary_department"`
	Position            *Position      `gorm:"foreignKey:PositionID;references:ID" json:"position"`
}

// TableName TenantMember's table name
func (*TenantMember) TableName() string {
	return TableNameTenantMember
}
