// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameVerificationCode = "verification_codes"

// VerificationCode 邮件短信验证码表
type VerificationCode struct {
	ID           uint64         `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:验证码主键" json:"id"`                                                      // 验证码主键
	UserID       uint64         `gorm:"column:user_id;type:bigint unsigned;not null;default:0;comment:关联用户ID，未知用户为0" json:"user_id"`                                               // 关联用户ID，未知用户为0
	Target       string         `gorm:"column:target;type:varchar(191);not null;index:idx_verification_codes_lookup,priority:1;comment:邮箱或手机号" json:"target"`                      // 邮箱或手机号
	Scene        string         `gorm:"column:scene;type:varchar(32);not null;index:idx_verification_codes_lookup,priority:2;comment:验证码场景：mfa登录，password_reset重置密码" json:"scene"` // 验证码场景：mfa登录，password_reset重置密码
	Channel      string         `gorm:"column:channel;type:varchar(16);not null;comment:发送渠道：email邮件，sms短信" json:"channel"`                                                        // 发送渠道：email邮件，sms短信
	CodeHash     string         `gorm:"column:code_hash;type:char(64);not null;comment:验证码SHA256摘要" json:"code_hash"`                                                              // 验证码SHA256摘要
	AttemptCount uint32         `gorm:"column:attempt_count;type:int unsigned;not null;default:0;comment:已验证失败次数" json:"attempt_count"`                                            // 已验证失败次数
	ExpiresAt    time.Time      `gorm:"column:expires_at;type:datetime(3);not null;comment:过期时间" json:"expires_at"`                                                                // 过期时间
	ConsumedAt   *time.Time     `gorm:"column:consumed_at;type:datetime(3);comment:消费时间" json:"consumed_at"`                                                                       // 消费时间
	ContextData  datatypes.JSON `gorm:"column:context_data;type:json;comment:MFA设备上下文等非敏感挑战数据" json:"context_data"`                                                                // MFA设备上下文等非敏感挑战数据
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime(3);not null;index:idx_verification_codes_lookup,priority:3;comment:创建时间" json:"created_at"`                 // 创建时间
}

// TableName VerificationCode's table name
func (*VerificationCode) TableName() string {
	return TableNameVerificationCode
}
