// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/sleep-go/kratos-admin/internal/data/model"
)

func newRoleScopeDepartment(db *gorm.DB, opts ...gen.DOOption) roleScopeDepartment {
	_roleScopeDepartment := roleScopeDepartment{}

	_roleScopeDepartment.roleScopeDepartmentDo.UseDB(db, opts...)
	_roleScopeDepartment.roleScopeDepartmentDo.UseModel(&model.RoleScopeDepartment{})

	tableName := _roleScopeDepartment.roleScopeDepartmentDo.TableName()
	_roleScopeDepartment.ALL = field.NewAsterisk(tableName)
	_roleScopeDepartment.ID = field.NewUint64(tableName, "id")
	_roleScopeDepartment.TenantID = field.NewUint64(tableName, "tenant_id")
	_roleScopeDepartment.RoleID = field.NewUint64(tableName, "role_id")
	_roleScopeDepartment.DepartmentID = field.NewUint64(tableName, "department_id")
	_roleScopeDepartment.CreatedAt = field.NewTime(tableName, "created_at")

	_roleScopeDepartment.fillFieldMap()

	return _roleScopeDepartment
}

type roleScopeDepartment struct {
	roleScopeDepartmentDo roleScopeDepartmentDo

	ALL          field.Asterisk
	ID           field.Uint64
	TenantID     field.Uint64
	RoleID       field.Uint64
	DepartmentID field.Uint64
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (r roleScopeDepartment) Table(newTableName string) *roleScopeDepartment {
	r.roleScopeDepartmentDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roleScopeDepartment) As(alias string) *roleScopeDepartment {
	r.roleScopeDepartmentDo.DO = *(r.roleScopeDepartmentDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roleScopeDepartment) updateTableName(table string) *roleScopeDepartment {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint64(table, "id")
	r.TenantID = field.NewUint64(table, "tenant_id")
	r.RoleID = field.NewUint64(table, "role_id")
	r.DepartmentID = field.NewUint64(table, "department_id")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *roleScopeDepartment) WithContext(ctx context.Context) IRoleScopeDepartmentDo {
	return r.roleScopeDepartmentDo.WithContext(ctx)
}

func (r roleScopeDepartment) TableName() string { return r.roleScopeDepartmentDo.TableName() }

func (r roleScopeDepartment) Alias() string { return r.roleScopeDepartmentDo.Alias() }

func (r roleScopeDepartment) Columns(cols ...field.Expr) gen.Columns {
	return r.roleScopeDepartmentDo.Columns(cols...)
}

func (r *roleScopeDepartment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roleScopeDepartment) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["id"] = r.ID
	r.fieldMap["tenant_id"] = r.TenantID
	r.fieldMap["role_id"] = r.RoleID
	r.fieldMap["department_id"] = r.DepartmentID
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r roleScopeDepartment) clone(db *gorm.DB) roleScopeDepartment {
	r.roleScopeDepartmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roleScopeDepartment) replaceDB(db *gorm.DB) roleScopeDepartment {
	r.roleScopeDepartmentDo.ReplaceDB(db)
	return r
}

type roleScopeDepartmentDo struct{ gen.DO }

type IRoleScopeDepartmentDo interface {
	gen.SubQuery
	Debug() IRoleScopeDepartmentDo
	WithContext(ctx context.Context) IRoleScopeDepartmentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoleScopeDepartmentDo
	WriteDB() IRoleScopeDepartmentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoleScopeDepartmentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoleScopeDepartmentDo
	Not(conds ...gen.Condition) IRoleScopeDepartmentDo
	Or(conds ...gen.Condition) IRoleScopeDepartmentDo
	Select(conds ...field.Expr) IRoleScopeDepartmentDo
	Where(conds ...gen.Condition) IRoleScopeDepartmentDo
	Order(conds ...field.Expr) IRoleScopeDepartmentDo
	Distinct(cols ...field.Expr) IRoleScopeDepartmentDo
	Omit(cols ...field.Expr) IRoleScopeDepartmentDo
	Join(table schema.Tabler, on ...field.Expr) IRoleScopeDepartmentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoleScopeDepartmentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoleScopeDepartmentDo
	Group(cols ...field.Expr) IRoleScopeDepartmentDo
	Having(conds ...gen.Condition) IRoleScopeDepartmentDo
	Limit(limit int) IRoleScopeDepartmentDo
	Offset(offset int) IRoleScopeDepartmentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoleScopeDepartmentDo
	Unscoped() IRoleScopeDepartmentDo
	Create(values ...*model.RoleScopeDepartment) error
	CreateInBatches(values []*model.RoleScopeDepartment, batchSize int) error
	Save(values ...*model.RoleScopeDepartment) error
	First() (*model.RoleScopeDepartment, error)
	Take() (*model.RoleScopeDepartment, error)
	Last() (*model.RoleScopeDepartment, error)
	Find() ([]*model.RoleScopeDepartment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoleScopeDepartment, err error)
	FindInBatches(result *[]*model.RoleScopeDepartment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RoleScopeDepartment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoleScopeDepartmentDo
	Assign(attrs ...field.AssignExpr) IRoleScopeDepartmentDo
	Joins(fields ...field.RelationField) IRoleScopeDepartmentDo
	Preload(fields ...field.RelationField) IRoleScopeDepartmentDo
	FirstOrInit() (*model.RoleScopeDepartment, error)
	FirstOrCreate() (*model.RoleScopeDepartment, error)
	FindByPage(offset int, limit int) (result []*model.RoleScopeDepartment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoleScopeDepartmentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roleScopeDepartmentDo) Debug() IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Debug())
}

func (r roleScopeDepartmentDo) WithContext(ctx context.Context) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roleScopeDepartmentDo) ReadDB() IRoleScopeDepartmentDo {
	return r.Clauses(dbresolver.Read)
}

func (r roleScopeDepartmentDo) WriteDB() IRoleScopeDepartmentDo {
	return r.Clauses(dbresolver.Write)
}

func (r roleScopeDepartmentDo) Session(config *gorm.Session) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Session(config))
}

func (r roleScopeDepartmentDo) Clauses(conds ...clause.Expression) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roleScopeDepartmentDo) Returning(value interface{}, columns ...string) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roleScopeDepartmentDo) Not(conds ...gen.Condition) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roleScopeDepartmentDo) Or(conds ...gen.Condition) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roleScopeDepartmentDo) Select(conds ...field.Expr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roleScopeDepartmentDo) Where(conds ...gen.Condition) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roleScopeDepartmentDo) Order(conds ...field.Expr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roleScopeDepartmentDo) Distinct(cols ...field.Expr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roleScopeDepartmentDo) Omit(cols ...field.Expr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roleScopeDepartmentDo) Join(table schema.Tabler, on ...field.Expr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roleScopeDepartmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roleScopeDepartmentDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roleScopeDepartmentDo) Group(cols ...field.Expr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roleScopeDepartmentDo) Having(conds ...gen.Condition) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roleScopeDepartmentDo) Limit(limit int) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roleScopeDepartmentDo) Offset(offset int) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roleScopeDepartmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roleScopeDepartmentDo) Unscoped() IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roleScopeDepartmentDo) Create(values ...*model.RoleScopeDepartment) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roleScopeDepartmentDo) CreateInBatches(values []*model.RoleScopeDepartment, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roleScopeDepartmentDo) Save(values ...*model.RoleScopeDepartment) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roleScopeDepartmentDo) First() (*model.RoleScopeDepartment, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleScopeDepartment), nil
	}
}

func (r roleScopeDepartmentDo) Take() (*model.RoleScopeDepartment, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleScopeDepartment), nil
	}
}

func (r roleScopeDepartmentDo) Last() (*model.RoleScopeDepartment, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleScopeDepartment), nil
	}
}

func (r roleScopeDepartmentDo) Find() ([]*model.RoleScopeDepartment, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoleScopeDepartment), err
}

func (r roleScopeDepartmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoleScopeDepartment, err error) {
	buf := make([]*model.RoleScopeDepartment, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roleScopeDepartmentDo) FindInBatches(result *[]*model.RoleScopeDepartment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roleScopeDepartmentDo) Attrs(attrs ...field.AssignExpr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roleScopeDepartmentDo) Assign(attrs ...field.AssignExpr) IRoleScopeDepartmentDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roleScopeDepartmentDo) Joins(fields ...field.RelationField) IRoleScopeDepartmentDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roleScopeDepartmentDo) Preload(fields ...field.RelationField) IRoleScopeDepartmentDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roleScopeDepartmentDo) FirstOrInit() (*model.RoleScopeDepartment, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleScopeDepartment), nil
	}
}

func (r roleScopeDepartmentDo) FirstOrCreate() (*model.RoleScopeDepartment, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleScopeDepartment), nil
	}
}

func (r roleScopeDepartmentDo) FindByPage(offset int, limit int) (result []*model.RoleScopeDepartment, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roleScopeDepartmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roleScopeDepartmentDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roleScopeDepartmentDo) Delete(models ...*model.RoleScopeDepartment) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roleScopeDepartmentDo) withDO(do gen.Dao) *roleScopeDepartmentDo {
	r.DO = *do.(*gen.DO)
	return r
}
